### ISSUE TITLE
deprecated issue of play2 json

### ISSUE THREAD

**Issue by ChokiZ** [ReactiveMongo/ReactiveMongo#1001]
### JDK (Oracle 1.8.0_231) scalaVersion := "2.12.7"

> Paste the output from `java -version` at the command line.

### Library Dependencies

If this is an issue that involves integration with other frameworks (e.g. Playframework), include the exact versions the other frameworks.
Play : 2.8.3

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. use sample code you provide in Play controller sample: http://reactivemongo.org/releases/1.0/documentation/tutorial/play.html, compile success

### Actual Behavior

1. compile err: value jsObjectWrites in package compat is deprecated (since 0.20.6): Will be removed when provided by Play-JSON itself

**Comment by cchantep** [comment]
As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md), this tracker is for confirmed issue, other please use the MailingList.
