### ISSUE TITLE
BSONDocument removes error fields during construction

### ISSUE THREAD

**Issue by saaryehudai** [ReactiveMongo/ReactiveMongo#1005]
### ReactiveMongo Version
1.0.1

### The Issue
`BSONDocument` ignores field-level errors from nested `BSONWriters`

Given
```scala
case class SomeType()
```
And a BSONWriter that outputs
```scala
Try(
  BSONDocument(
    "key" => "SomeKey",
    "SomeType" => SomeType()
  )
)
```
The scenario happens when `BSONWriter[SomeType]` throws an exception 

### Expected Behavior
`Failure[BSONDocument]`

### Actual Behavior
`Success[BSONDocument]` with a single "key" field in the document.
"SomeType" field will not exist on the document. 

### Reproducible Test Case
```scala
package test.reactive.mongo

import org.scalatest._
import reactivemongo.api.bson._
import scala.util.Try

class Test extends WordSpec with Matchers{

  case class SomeType()
  implicit val serde = new BSONDocumentWriter[SomeType] with BSONDocumentReader[SomeType] {
    override def writeTry(a: SomeType): Try[BSONDocument] =
      Try(throw new UnsupportedOperationException())
    override def readDocument(doc: BSONDocument): Try[SomeType] =
      Try(throw new UnsupportedOperationException())
  }

  "BSONDocument" must {
    "ignore field level serialization errors" in {
      val doc = Try(
        BSONDocument(
          "a" -> SomeType(),
          "b" -> "B"
        )
      )

      doc.isSuccess shouldBe true
      doc.get.elements.length shouldBe 1
      doc.get.elements(0).value shouldBe BSONString("B")
    }
  }
}
```

**Comment by cchantep** [comment]
Hi,

As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), this tracker is for confirmed issue, other please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).

As you use the convenient factory automatically converting Scala values to BSON values, invalid values are ignored.
In coherence with the return type, it will never throw an `Exception`.

If you want to handle explicitly writers exception, call them and use `BSONDocument(Seq("foo" -> bsonValue))`.

**Comment by cchantep** [comment]
Also could have a look at https://oss.sonatype.org/service/local/repositories/snapshots/archive/org/reactivemongo/reactivemongo-bson-api_2.13/1.0.2-SNAPSHOT/reactivemongo-bson-api_2.13-1.0.2-SNAPSHOT-javadoc.jar/!/reactivemongo/api/bson/BSONDocument$.html#safe(elms:reactivemongo.api.bson.ElementProducer*):scala.util.Try[reactivemongo.api.bson.BSONDocument]

**Comment by saaryehudai** [comment]
Thanks for replying & sorry for the misunderstanding...
I now see you are right, the type indicates no errors are expected. 
We've implemented our own factory to be able to get the desired behavior. 

Thanks 🙏
