### ISSUE TITLE
Aggregation Merge is treating DB and Collection incorrectly

### ISSUE THREAD

**Issue by cleger-decentrix** [ReactiveMongo/ReactiveMongo#1011]
https://github.com/ReactiveMongo/ReactiveMongo/blob/1302cbcc5b6a105bd211068633a404af723d8701/driver/src/main/scala/api/commands/AggregationFramework.scala#L1003

ReactiveMongo _always_ makes a `db.collection` string for the `into` parameter, but Mongo accepts _two_ forms:
* single string for the `collection`, when run within a Database
* a document describing the `db` and `coll` separately

https://docs.mongodb.com/v4.2/reference/operator/aggregation/merge/#merge-into

With ReactiveMongo's behavior, it doesn't seem possible to run an Aggregation inside a Collection (where ideally you'd not specify the DB), since the resulting string would be `.collection` and is invalid.

**Comment by cchantep** [comment]
Hi,

Technically speaking, always requiring the DB is not incorrect. A collection is always in a DB, and this merge stage being able to merge in the same or in a different DB is more useful than the one for only the same DB.

It could be convenient to omit the DB when it's the same for both collections, then it's an improvement, not an issue to be fixed, that we will have a look at.

Meanwhile, it's quite easy to always pass the DB name.

Also, as [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), please rather use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question/discuss what you think could be improvements.

Best regards.
