### ISSUE TITLE
Read preference tags are not working on 1.x

### ISSUE THREAD

**Issue by dkovalenko** [ReactiveMongo/ReactiveMongo#1024]
### ReactiveMongo Version
1.0.2

### MongoDB version 
4.2.11

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Unutu Linux 20 , mac OS 11.2

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk 11, graalvm 11

### Library Dependencies

Play 2.7
circe-bson 0.5.0

### Expected Behavior

1. I have mongo cluster with 2 datacenters. I set instance tags to {"dc":"dc1"} and {"dc":"dc2"}. I have primary instance in dc1.
2. I have read preference in my code set to secondaryPreferred {"dc":"dc1"}
3. Reads go to mongo instance with **dc1** tag

### Actual Behavior
3.  I upgraded my reactive mongo lib from version "0.19.0" to "1.0.2"
4. When i run application in mongodb ops manager I see that queries goes to **dc2**
5. I tried version to rollback library to version "0.19.0" - trafic goes to **dc1**

So read preference with tags is working improperly in 1.x branch.

**Comment by cchantep** [comment]
You can try 1.0.4-SNAPSHOT

**Comment by dkovalenko** [comment]
> You can try 1.0.4-SNAPSHOT

Did you publish that to maven central? I'm using play2-reactivemongo as dependency.

**Comment by cchantep** [comment]
Snapshots are only on sonatype OSs snapshots

**Comment by dkovalenko** [comment]
Did you fix the bug? Can we expect a release anytime soon?

**Comment by cchantep** [comment]
As said previously, it's already in the snapshot.

**Comment by dkovalenko** [comment]
Thank you!

**Comment by cchantep** [comment]
Published in 1.0.4

**Comment by dkovalenko** [comment]
Thank you, it works!
