### ISSUE TITLE
two serious problems in high concurrence

### ISSUE THREAD

**Issue by wenrenren** [ReactiveMongo/ReactiveMongo#1069]
1、Sometimes queries do not return data,but data is exists;
2、cursor don't close when find is over. This cause a large amount of memory being occupied.

It makes me give up  this lib, scala.mongo.driver don't exist these problems.

**Comment by cchantep** [comment]
Hi,

1. Saying it doesn't work without details is not constructive.
2. Saying it doesn't work or it use too much memory without details is not constructive.
3. Creating a GitHub issue just to say you are not happy is not constructive.
4. If you read the issue guideline, you can see that to discuss/ask question, GitHub is not the place, but that there is a [MailingList](https://groups.google.com/g/reactivemongo).

Best regards,
