### ISSUE TITLE
Find distinct field

### ISSUE THREAD

**Issue by tianjianfeng** [ReactiveMongo/ReactiveMongo#110]
Hi, 

Anybody knows how to retrieve distinct fields in reactivemongo. 

In command line it is: db.coll.distinct("field")

But couldn't find the distinct api in reactivemongo. 

thanks

**Comment by francisdb** [comment]
Any reason for not providing this natively?

**Comment by scalastic** [comment]
You can find a specific implementation here : https://github.com/analytically/mapmailer/blob/master/app/reactivemongo/commands.scala

**Comment by cchantep** [comment]
This implementation is based on an a command API which will be deprecated in the 0.11 driver. Using the new [`RawCommand`](http://reactivemongo.org/releases/0.11.0/documentation/advanced-topics/commands.html) it can be executed easily. Let discuss on the [Mailing list](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to see whether it deserves a specific command class in the API. Best regards.

**Comment by scalastic** [comment]
So you're right. 
However designing an API over `RawCommand` would be handsome !

Best regards.

**Comment by cchantep** [comment]
That's can be planed as an improvement.
