### ISSUE TITLE
How to log down the raw queries?

### ISSUE THREAD

**Issue by Frederic-Avetta** [ReactiveMongo/ReactiveMongo#1148]
Hello, in case of performance tuning, I need to see or log down the raw/native queries or aggregation.
How could I do that?

Thanks and regards

**Comment by cchantep** [comment]
Hi,

As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), this issue tracker is not for asking question.

There is things such as raw/native queries.
If you have a look at the documentation, you can see how to [pretty print any `BSONDocument`](https://javadoc.io/static/org.reactivemongo/reactivemongo-bson-api_3/1.1.0-noshaded-RC5/reactivemongo/api/bson/BSONDocument$.html#pretty-5e7).
