### ISSUE TITLE
Connectivity issues with Azure Cosmos API

### ISSUE THREAD

**Issue by abhisheksharma85** [ReactiveMongo/ReactiveMongo#1158]
### Are you looking for help?

> Connectivity issues with Azure Cosmos Mongo API

### MongoDB version
> We are using Azure Cosmos Mongo API. So, we don't know any specific MongoDB version

### JDK (Oracle 1.8.0_292-b10, OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10))

> openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

### Library Dependencies

> Playframework-27
play2_reactivemongo_2.12:1.0.10-play27

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Using connection string 
mongodb://abhishek-dev-db:{password}@abhishek-cosmos-dev-cosmos.mongo.cosmos.azure.com:10255/movies?ssl=true&maxIdleTimeMS=20000&rm.keepAlive=true&rm.tcpNoDelay=true&appName=@movies-cosmos-dev-cosmos@
2. Should maintain a consistent connection pool and recover connection (if failure)
3. strictUri=true

### Actual Behavior
Getting different errors, random and inconsistent
1. "MongoError['No authenticated channel for the primary node:
2. "MongoError['No primary node is available!
3. Connection lost very often 

Please provide a description of what actually happens, working from the same starting point.

1. Reading data from a source and writing to MongoDB (Azure Cosmos MongoDB)
2. For each record we write to Cosmos we first look for that record using an id
3. if records exists we skip else we run an insert query
4. We are processing at least 100,000 records.

### Reproducible Test Case

Process 100,00 or more queries

**Comment by cchantep** [comment]
As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), this issue tracker is for confirmed issue, not to ask for help.

Please rather use StackOverflow or [MailingList](https://groups.google.com/g/reactivemongo).

> BTW "Process 100,00 or more queries" is not a reproducer.
