### ISSUE TITLE
[new][atlas] Add "score" attribute to all the operators

### ISSUE THREAD

**Issue by YanDoroshenko** [ReactiveMongo/ReactiveMongo#1165]
Atlas search supports "score" parameter in [other operators](https://www.mongodb.com/docs/atlas/atlas-search/operators-and-collectors/), not just the "leaf" ones (regex, queryString, range, etc.).
Add scoring support for all the operators that support it on the Atlas side.

**Comment by cchantep** [comment]
Thanks for the feedback.

> Please note that "If you have a feature request, please first raise it on the [mailing list](https://groups.google.com/forum/#!forum/reactivemongo)."
