### ISSUE TITLE
Fails to send isMaster

### ISSUE THREAD

**Issue by mohdmsl** [ReactiveMongo/ReactiveMongo#1176]
I am using  
 "org.reactivemongo" %% "play2-reactivemongo" % "1.1.0-play28-RC3",

and I am getting below error:
**[[31merror[0m] r.c.a.MongoDBSystem - [Supervisor-1/datapipeline] Fails to send a isMaster request to mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017 (channel #e7e125a4)**

is there any configuration I need to give in connectionString or what can be the root cause. I didnt find anything in documentation

**Comment by cchantep** [comment]
As indicated in the guide line, this tracker must not be use to ask question/for help.
Rather use the [mailinglist](https://groups.google.com/g/reactivemongo).
