### ISSUE TITLE
Loses connection after 30 seconds

### ISSUE THREAD

**Issue by ornicar** [ReactiveMongo/ReactiveMongo#1182]
- ReactiveMongo 1.1.0-RC6
- MongoDB 5.0.13
- Linux 5.19.11-arch1-1
- OpenJDK 17.0.5
- scala 3.2.1 (also happens with 2.13.10)
- with and without playframework

When launching a project using reactivemongo 1.1.0-RC6, such as lila (playframework) or lila-ws (non playframework), reactivemongo seems to lose connection after about 30 seconds. It logs errors, and queries fail.
The problem did not exist on version 1.0.10.

I made a little repository with details and a minimal reproduction environment: https://github.com/ornicar/rm-issue

Note that it does not happen every time with that repo, for reasons yet unknown.
But it does happen every time when running lila or lila-ws.

I'll post more info as I keep digging into this.

**Comment by ornicar** [comment]
I found that creating 2 connections with the same driver allows to reproduce it consistently after just 10s.

```scala
  val driver = new AsyncDriver

  (1 to 2).toList map { i =>
    Await.result(
      for
        conn <- driver.connect(List("localhost:27017"))
        db <- conn.database(s"test-rm-$i")
      yield db,
      3.seconds
    )
  }

  for i <- 0 to 12 do
    println(i)
    Thread sleep 1000

  driver.close()
```
root> runMain Minimal
[info] running Minimal
[sbt-bg-threads-9] INFO reactivemongo.api.Driver - [Supervisor-1] Creating connection: Connection-1
[reactivemongo-akka.actor.default-dispatcher-5] INFO reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-1] Starting the MongoDBSystem
[reactivemongo-akka.actor.default-dispatcher-5] INFO reactivemongo.core.netty.Pack - Instantiated reactivemongo.core.netty.Pack
[sbt-bg-threads-9] INFO reactivemongo.api.Driver - [Supervisor-1] Creating connection: Connection-2
[reactivemongo-akka.actor.default-dispatcher-5] INFO reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Starting the MongoDBSystem
[reactivemongo-akka.actor.default-dispatcher-5] INFO reactivemongo.core.netty.Pack - Instantiated reactivemongo.core.netty.Pack
0
1
2
3
4
5
6
7
8
9
10
[reactivemongo-akka.actor.default-dispatcher-6] WARN reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] The entire node set is unreachable, is there a network problem?
11
12
[sbt-bg-threads-9] INFO reactivemongo.api.Driver - [Supervisor-1] Closing instance of ReactiveMongo driver
```

**Comment by cchantep** [comment]
Will have a look

**Comment by cchantep** [comment]
You can try `1.1.0-RC7-SNAPSHOT`

**Comment by cchantep** [comment]
And `1.1.0-275c4ca-RC7-SNAPSHOT`

**Comment by ornicar** [comment]
Thank you for looking into this! In which repository are these published?

**Comment by ornicar** [comment]
nevermind, found them in https://oss.sonatype.org/content/repositories/snapshots

**Comment by ornicar** [comment]
Yes, I can't reproduce it in the test project either, no matter how many connections I make :) Awesome! Can't wait to see what the fix looks like :+1:

**Comment by cchantep** [comment]
Thx, will publish fix (idle limit on signaling channel needs some update)

**Comment by ornicar** [comment]
I deployed this minimal stream program to prod and connected it to the prod databases https://github.com/ornicar/rm-issue/blob/master/src/main/scala/stream.scala
and it just worked perfectly. So I can't yet reproduce/debug the problem.

**Comment by ornicar** [comment]
I managed to reproduce it consistently, all it needed was to read from a secondary.

I made a new issue for it: https://github.com/ReactiveMongo/ReactiveMongo/issues/1185

**Comment by cchantep** [comment]
Published 1.1.0-d9cc5339-RC7-SNAPSHOT with more appropriate fix

**Comment by ornicar** [comment]
Awesome, thank you! Will try it out in prod very soon.

**Comment by ornicar** [comment]
Is the code published on another public repo?

**Comment by cchantep** [comment]
1.1.0-RC7 published: https://search.maven.org/artifact/org.reactivemongo/reactivemongo_2.13/1.1.0-RC7/jar
