### ISSUE TITLE
Upgrade Akka to 2.6.x for Scala 2.12/2.13

### ISSUE THREAD

**Issue by artemvedernikov** [ReactiveMongo/ReactiveMongo#1205]
Latest versions of ReactiveMongo for Scala 2.12 / 2.13 now use outdated Akka version 2.5.32
It would be great to have Akka version upgraded  to more recent 2.6.x

**Comment by cchantep** [comment]
As indicated in the documentation, ReactiveMongo supports Akka dependency from 2.3 to 2.6, just explicit the dependency in the build.

Also as indicated in this issue tracker is for confirmed issue.
Please use the [MailingList](https://groups.google.com/g/reactivemongo) or [StackOverflow](https://stackoverflow.com/questions/tagged/reactivemongo) to ask question.
