### ISSUE TITLE
There's misleading naming for timestamp in change stream's StartAt

### ISSUE THREAD

**Issue by Azadios** [ReactiveMongo/ReactiveMongo#1249]
https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/commands/ChangeStreamAggregation.scala#L128C15
It is called `operationTime`, and it seems as if it should represent the usual milliseconds from the start of the epoch. However, from what I can see, this Long value is directly used in the default BSONSerializationPack, resulting in a BSONTimestamp. This BSONTimestamp is far from typical; it's a combination of time and ordinal. Perhaps a renaming is in order, or there should be a change in the signature for StartAt to use `time: Int, ordinal: Int`, which would be much more explicit and intuitive.

**Comment by cchantep** [comment]
Hi,

The naming `operationTime` corresponds to the MongoDB documentation, so as for now, not reason to change it.

> Specifies a resume token as the logical starting point for the change stream. Cannot be used with resumeAfter or startAtOperationTime fields.

As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help) this issue tracker is not for discussion/asking question.
