### ISSUE TITLE
`reactivemongo` 1.1.0-RC12-SNAPSHOT depends on `akka`

### ISSUE THREAD

**Issue by Fristi** [ReactiveMongo/ReactiveMongo#1264]
With the following setup

```
Seq(
    "org.reactivemongo" %% "reactivemongo"                 % "1.1.0-RC12-SNAPSHOT",
    "org.reactivemongo" %% "reactivemongo-actors-pekko"    % "1.1.0-RC12-SNAPSHOT"
)
```

The `reactivemongo` module still uses the akka. 

See https://oss.sonatype.org/content/repositories/snapshots/org/reactivemongo/reactivemongo_2.12/1.1.0-RC12-SNAPSHOT/reactivemongo_2.12-1.1.0-RC12-SNAPSHOT.pom

This is probably due to https://github.com/ReactiveMongo/ReactiveMongo/blob/master/project/Common.scala#L13

So for a publish it's been published with a hard link on the actor module of Akka?

**Comment by cchantep** [comment]
As for shared it will need to be taken in account in versioning.

**Comment by Fristi** [comment]
So from what I understand we need to build the driver for both akka and pekko and publish it with a special version? Why not as `reactivemongo-akka` and `reactivemong-pekko` ?

**Comment by cchantep** [comment]
That's a variant not an artifact name.

**Comment by Fristi** [comment]
We wanted to forward with this and therefore I've published the artifacts myself.

# BIY (build it yourself)

## Start sbt
To actual publish the `reactivemongo` module (which is the driver) and relies on either the akka or pekko version you have to set the env var `ACTOR_SYSTEM` to `pekko`.

```
ACTOR_SYSTEM=pekko sbt
```

## Version pinned
In `version.sbt` pin the version to `ThisBuild / version := "1.1.0-RC12-SNAPSHOT"` for example

## .jvmopts
In this file I removed the flag `-XX:+CMSClassUnloadingEnabled` to make it work on my machine

## Publish.scala
For me some of the published artifacts only contained documentation? To fix this I changed

```
    artifactName := { (sv: ScalaVersion, module: ModuleID, artifact: Artifact) =>
      s"${artifact.name}$modulePostfix-${module.revision}.${artifact.extension}"
    }
```

to 

```
    artifactName := {
      (sv: ScalaVersion, module: ModuleID, artifact: Artifact) =>
        Artifact.artifactName(sv, module, artifact)
    }
```

# Final usage in my build.sbt

```
libraryDependencies ++= Seq(
  "org.reactivemongo"          %% "reactivemongo"              % "1.1.0-RC12-SNAPSHOT",
  "org.reactivemongo"          %% "reactivemongo-core"         % "1.1.0-RC12-SNAPSHOT",
  "org.reactivemongo"          %% "reactivemongo-actors-pekko" % "1.1.0-RC12-SNAPSHOT",
)
```

Hopefully in future releases the module `reactivemongo` is both published for akka and pekko, for the time being if anyone needs this solution you can

Have a nice day writing Scala!
