### ISSUE TITLE
Transparent upgrade of replicaset Atlas MongoDB 5 -> 6 seems not to be supported

### ISSUE THREAD

**Issue by michael-on-the-job** [ReactiveMongo/ReactiveMongo#1312]
### Expected Behavior

Application is connected to Atlas MongoDB replicaset v5.0.26 (via mongodb+srv option) and working correctly.

Atlas MongoDB replicaset is triggered to upgrade to v6.0.15 (Replicaset nodes are upgraded one-by-one, starting with secondaries, primary last. Primary will change then)

Expected: Driver is keeping track of replicaset nodes and communicating with replicaset nodes. DB operations continue to work.

### Actual Behavior

Some time after triggering replicaset upgrade, all DB Operations fail with "r.c.e.DatabaseException$$anon$1: DatabaseException['Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal' (code = 352)]"

Already our analysis:

When the MongoDB 5 replicaset is upgraded, the driver seems to connect to MongoDB 6 nodes still with MongoDB 5 protocol: 
We see a lot of logs that changes in the replicaset are actually detected.
Before triggering the upgrade logs are shown "A primary is available: ProtocolMetadata(3.0, 5.0)"
After upgrade in fact logs are shown "A primary is available: ProtocolMetadata(3.0, 6.0)" - still those errors occur.

A complete restart of the application (and thus completely new connect to the MongoDB 6 replicaset) solves the problem. Driver is actually capable of working correctly with MongoDB 6.

### Reproducible Test Case

We think this a general issue, we reproduced it several times with different applications using reactive mongo driver  1.1.0-RC12. 
The test setup necessary to be done is not the app, it is triggering the upgrade of the replicaset the driver is connected to.

**Comment by cchantep** [comment]
Please do not duplicate discussion there and on the mailinglist.
