### ISSUE TITLE
Support for MongoDB built with SSL

### ISSUE THREAD

**Issue by ryknow** [ReactiveMongo/ReactiveMongo#145]
I have been creating a Scala Play application and would like to use ReactiveMongo, but as far as I can tell there isn't any way to provide SSL options when creating a database connection.  Are there any plans to add support for connecting to a MongoDB that has been built with SSL support?

**Comment by dlpatri** [comment]
What's the status on this? Is there a fork/branch compatible with 0.10.5.0.akka23?

**Comment by cchantep** [comment]
Hi guys. Those interested could give a try to SSL support on master #286 .

**Comment by shreyaspurohit** [comment]
Can we please have a release with this patch? SSL support if pretty important to wait till 0.11 release.

**Comment by cchantep** [comment]
The milestone 0.11.0-M1 can be used (published on Maven central repo).

**Comment by duncancrawford** [comment]
@cchantep thanks for releasing a milestone. Can you tell me what is in 0.11.0-M1 over and above this fix?

**Comment by cchantep** [comment]
0.11.0-M1 is feature complete : new command API, SSL support, MongoDB 3 support, new streaming API, convenient collection operations (count, runCommand).

No change is planned for the driver from M1 to release (still some work on the Play plugin), but documentation.

**Comment by duncancrawford** [comment]
excellent! and thanks

**Comment by shreyaspurohit** [comment]
Awesome! Thanks a lot!

**Comment by epot** [comment]
Is it now available in 0.11.4 ? Because I am using this very latest version and I still get this warning when trying to connect to a Mongo URI with SSL:
Some options were ignored because they are not supported (yet): ssl

**Comment by cchantep** [comment]
@epot I suggest you have a look at the [documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/connect-database.html) to check which SSL options are available. For more question, then please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo). Best regards.
