### ISSUE TITLE
Why connection crashes with no reason ?

### ISSUE THREAD

**Issue by lucasrpb** [ReactiveMongo/ReactiveMongo#146]
I am using ReactiveMongo in a play 2.2 app. Its very good! But sometimes the connection crashes with no apparent reason. Then this message is printed out many times:

11:18:04.344 [reactivemongo-akka.actor.default-dispatcher-3] ERROR reactivemongo.core.actors.MongoDBSystem - The entire node set is unreachable, is there a network problem?

Alright... I manually restart mongodb in command line with:
sudo launchctl unload /Library/LaunchDaemons/org.mongodb.mongod.plist 
followed by 
sudo launchctl load /Library/LaunchDaemons/org.mongodb.mongod.plist 

The reactivemongo driver should be reconnect but nothing happens. At the same time when I try connect to mongo shell I receive this error:

Thu Jan  9 11:11:18.624 DBClientCursor::init call() failed
Thu Jan  9 11:11:18.625 Error: DBClientBase::findN: transport error: 127.0.0.1:27017 ns: admin.$cmd query: { whatsmyuri: 1 } at src/mongo/shell/mongo.js:145
exception: connect failed

When I quit from play app, then mongo shell works. This is so weird! What is happening? This kind of behavior is not acceptable in production environments.

**Comment by cchantep** [comment]
I think this one can be closed now.
