### ISSUE TITLE
[enhancement] Custom naming strategies for keys (CamelCase, under_scores...)

### ISSUE THREAD

**Issue by crumbpicker** [ReactiveMongo/ReactiveMongo#149]
It would be awesome if reactivemongo could support custom naming strategies for the keys of BSON fields (as it is possible with Jackson and GSON).
I have reported a similar issue for the pickling library (https://github.com/scala/pickling/issues/34).

I would like to use a lower case convention instead of CamelCase.
Currently as a workaround I'm using the new @Key annotation but it's a lot of boilerplate I would like to avoid.

**Comment by cchantep** [comment]
Close it for now. Can be discussed on the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo). Best regards.
