### ISSUE TITLE
Incorrect reporting of "entire nodeset is unavailable"

### ISSUE THREAD

**Issue by RayRoestenburg** [ReactiveMongo/ReactiveMongo#158]
version 0.10-snapshot (but master code is the same)

We are seeing "entire nodeset is unavailable" error messages while connected to a cloud hosted mongo instance. It looks like this is reported incorrectly. Not often but at times where the application is doing hardly any work (or even no work).  

Looking at the code in actors.scala (line 305 till 345) it looks like any channel that is closed or disconnected can eventually lead to a new nodeset with all nodes in unknown state, which then immediately causes that the error is logged, while it could well be that the status of the nodes is unknown temporarily. The MongoDB server could close or disconnect (idle) channels at any time (which I think sounds fair), and still allow new channels, which means the nodeset is actually not unreachable.

IMHO the driver should check the unknown state of the nodes before logging an error that the nodeset is unreachable. For instance it could try to create new connections and set the correct status when these have successfully connected to the MongoDB instance, and only if it cannot connect to any node, report the error.

**Comment by cchantep** [comment]
Let close this for now. Can be reopened if still reported after release of 0.11.0. Best regards.
