### ISSUE TITLE
Expire Data Command

### ISSUE THREAD

**Issue by gaetansenn** [ReactiveMongo/ReactiveMongo#193]
Hi,

Anybody knows how to retrieve Expire Data with ensureIndex in reactivemongo.

In command line it is: db.log_events.ensureIndex( { "createdAt": 1 }, { expireAfterSeconds: 3600 } )

But couldn't find the distinct api in reactivemongo and i don't really know how to use with a RawCommand 

PS: (i'm using Scala)

thanks

**Comment by cchantep** [comment]
Hi,

Please have a look at the [command API documentation](http://reactivemongo.org/releases/0.11/documentation/advanced-topics/commands.html#run-any-command-with-rawcommand).

For more question, please use the [user Mailing List](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo).

Best regards
