### ISSUE TITLE
0.10.2: Cursor.enumerate & Cursor.enumerateBulks maxDocs parameter not used

### ISSUE THREAD

**Issue by marcuslinke** [ReactiveMongo/ReactiveMongo#197]
It seems to me that the maxDocs parameter of both methods is not used. Setting it to '1' doesn't limit the documents that are enumerated.

**Comment by cchantep** [comment]
Fixed in [PR #296](https://github.com/ReactiveMongo/ReactiveMongo/pull/296/files).
