### ISSUE TITLE
reactivemongo.api.collections.default.BSONCollection missing

### ISSUE THREAD

**Issue by xumbino** [ReactiveMongo/ReactiveMongo#210]
Hello, 

probably after your last merge, I'm not able to import BSONCollection from default package as it does not exist. 

If that behavior is intended you should do it in a new branch.

For now I downgraded to 0.10.5-akk23 instead of 0.11.0-SNAPSHOT

**Comment by shravanc** [comment]
Hi, Am new to scala and In the project I am learning is importing reactivemongo.api.collections.default.BSONCollection . Am facing issues, have installed all latest versions. Please let me know how to fix this, error is as below:

object default is not a member of package reactivemongo.api.collections

**Comment by cchantep** [comment]
Hi, as you can see in the [scaladoc](http://reactivemongo.org/releases/0.11/api/index.html#reactivemongo.api.collections.package), the `BSONCollection` was moved to another package since 0.11.0 . Best regards.

> This issue tracker is for confirmed issue or actionable feature request. Please first ask on the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo).
