### ISSUE TITLE
Ensure unique index issue

### ISSUE THREAD

**Issue by ArchDev** [ReactiveMongo/ReactiveMongo#215]
Hello. I have a problem with unique index creation. When I use collection.indexesManager.ensure() like this:
```
collection.indexesManager.ensure(Index(Seq("username" -> IndexType.Hashed), background = true))
```
indexes creating correctly, but when I trying to create unique index like this:

```
collection.indexesManager.ensure(Index(Seq("username" -> IndexType.Hashed), unique = true, background = true))
```
indexes dont creating, but I have no exception or something that indicate me about error.

All tests performs with new collections and collection with some data.

**Comment by wertlex** [comment]
Hashed index cannot be unique. It is a Mongo restriction.

**Comment by ArchDev** [comment]
Thanks, I'm sorry for inappropriate question.
