### ISSUE TITLE
understanding of reactive driver best practises and real life use case question

### ISSUE THREAD

**Issue by reviyou** [ReactiveMongo/ReactiveMongo#216]
Hello,
we are writing to you in hope to get some clarify on best practices of non-blocking mongoddb driver usage.

How using non blocking driver affects connection pool? Should we still limit amount of the database requests to a minimum for better scalability?.

Let's say we need to show 10 objects on the UI for 1 user.
option 1 is to asynchronously show and load those objects from db
option 2 is to make 1 request to load all objects form db and show them on the ui at once

with sql databases most of the case option1 is preffered for better scalability and to limit amount of connections.

We'd like to know complications of using option #2 with non blocking driver and your thoughts on whether or not it gets us a better db performance with let's say 10000 concurrent users trying to load those 10 objects.

Regards,
~R

**Comment by cchantep** [comment]
Hi the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) is a good place for such question. Best regards.

**Comment by reviyou** [comment]
We already did that and received answers. Thanks for the follow up
