### ISSUE TITLE
Connection URI does not support the read preferences and write concern options

### ISSUE THREAD

**Issue by Shinbuev** [ReactiveMongo/ReactiveMongo#219]
ReactiveMongo driver doesn't support the read preferences and write concern options in connection uri.
It would be nice to follow the documentation on 10gen regarding connection string format:
http://docs.mongodb.org/manual/reference/connection-string/

api.scala MongoConnection
```
    def makeOptions(opts: Map[String, String]): (List[String], MongoConnectionOptions) = {
      opts.iterator.foldLeft(List.empty[String] -> MongoConnectionOptions()) { case ((unsupportedKeys, result), kv) =>
        kv match {
          case ("authSource", v)           => unsupportedKeys -> result.copy(authSource = Some(v))
          case ("connectTimeoutMS", v)     => unsupportedKeys -> result.copy(connectTimeoutMS = v.toInt)

          case ("rm.tcpNoDelay", v)        => unsupportedKeys -> result.copy(tcpNoDelay = v.toBoolean)
          case ("rm.keepAlive", v)         => unsupportedKeys -> result.copy(keepAlive = v.toBoolean)
          case ("rm.nbChannelsPerNode", v) => unsupportedKeys -> result.copy(nbChannelsPerNode = v.toInt    )

          case (k, _) => (k :: unsupportedKeys) -> result
        }
      }
    }
```

**Comment by saml** [comment]
Looks like write concern and journal options are completely missing: http://reactivemongo.org/releases/0.10.5/api/index.html#reactivemongo.api.MongoConnectionOptions

Is this intentional?
Is there a workaround to specify write concern and journal and other options when connecting to mongodb?

**Comment by cchantep** [comment]
The read preference & write concern are managed per-call (not as global connection option), on collection functions: http://reactivemongo.org/releases/0.10.5/api/index.html#reactivemongo.api.collections.GenericCollection .

Please first ask such question on the [Mailing list](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo).

Best regards
