### ISSUE TITLE
Documentation needs warning about single threaded CPUs

### ISSUE THREAD

**Issue by xumbino** [ReactiveMongo/ReactiveMongo#223]
I've been hitting my head against the table the last week because something was wrong. After a lot debug and a search in google I came to find this

https://groups.google.com/forum/#!topic/play-framework/Gi1V7qDjE6E

And Johan Andren answer solved my problem.

I think you should put in red color that "limitation/requirement" and throw some kind of warning or exception in your code.

I was getting stuck when I tried to find something in a collection and was getting a timeout.

**Comment by sgodbillon** [comment]
Sorry, I don't see how it could be related to single-threaded CPUs in any way... ReactiveMongo does not block any thread, never ever.

**Comment by xumbino** [comment]
I don't know either because it's strange, but as soon as I changed my virtual machine properties to use 4 cores of the CPU this started working

**Comment by sgodbillon** [comment]
There was maybe something else somewhere in your code or in the libraries you use, that blocked a thread of the Akka dispatcher (the Play plugin uses Play's Akka system by default)...

**Comment by xumbino** [comment]
I wasnt using Play.. I couldn't debug very well on that VM because it was Ubuntu Server.. But from what I could gather it stopped when I was accessing the database and getting timeouts.. 

It was sometime ago, so I don't really remember that well

**Comment by cchantep** [comment]
I guess it can be closed for now.
