### ISSUE TITLE
Authentication failure using 0.10.5.0.akka23 on deployment on Heroku

### ISSUE THREAD

**Issue by wir33658** [ReactiveMongo/ReactiveMongo#224]
Getting the similar error as in

https://github.com/ReactiveMongo/ReactiveMongo/issues/107

which was concidered fixed (and there is also something on Heroku https://github.com/ReactiveMongo/ReactiveMongo/issues/109)

Me, I am trying to deploy my app on Heroku and get :

Dec 03 23:54:24 lit-sands-7031 app/web.1:  MongoBlogProvider: got blogs for None 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  07:54:26.942 [ForkJoinPool-3-worker-7] ERROR reactivemongo.api.Failover - Got an error, no more attempts to do. Completing with a failure... 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on test.BlogCollection' (code = 16550)] 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  	at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32) ~[org.reactivemongo.reactivemongo_2.11-0.10.5.0.akka23.jar:0.10.5.0.akka23] 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  	at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:263) ~[org.reactivemongo.reactivemongo_2.11-0.10.5.0.akka23.jar:0.10.5.0.akka23] 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  	at reactivemongo.core.protocol.Response.error(protocol.scala:258) ~[org.reactivemongo.reactivemongo_2.11-0.10.5.0.akka23.jar:0.10.5.0.akka23] 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  	at reactivemongo.core.actors.MongoDBSystem$$anonfun$receive$1.applyOrElse(actors.scala:443) ~[org.reactivemongo.reactivemongo_2.11-0.10.5.0.akka23.jar:0.10.5.0.akka23] 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[com.typesafe.akka.akka-actor_2.11-2.3.6.jar:?] 
Dec 03 23:54:27 lit-sands-7031 app/web.1:  	at reactivemongo.core.actors.MongoDBSystem.aroundReceive(actors.scala:96) ~[org.reactivemongo.reactivemongo_2.11-0.10.5.0.akka23.jar:0.10.5.0.akka23] 

I am using :

scalaVersion := "2.11.1"
"org.reactivemongo" %% "reactivemongo" % "0.10.5.0.akka23"

My Procfile for Heroku (should be fine since its starting):

web: target/universal/stage/bin/play-scala -Dhttp.port=$PORT -Dmongodb.uri=$MONGOHQ_URL

(And yes, I do have a MongoHQ add-on running on my Heroku-Dyno).

---------------------------------------------------------------

I use the following code for testing it locally (so not on heroku) :

In application.conf : 
mongodb.uri="mongodb://user22:userpw22@127.0.0.1:27017/test"

In code :
      val mongouri = Play.configuration.getString("mongodb.uri").getOrElse("mongodb://127.0.0.1:27017")
      val driver = new MongoDriver
      val connection = MongoConnection.parseURI(mongouri).map { parsedURI =>
        driver.connection(parsedURI)
      }

And I simply continue, but there is not this user and I whould expect an authorization error/exception.

Printing out the parsedURI : ParsedURI(List((127.0.0.1,27017)),MongoConnectionOptions(0,None,true,true,10),List(),Some(test),Some(Authenticate(test, user22)))

If I do 

val fauth = db.authenticate("admin", "admin")(5000 millis)

this will give me an expected result if the admin is there it continues if not it fails. (This behaviour I would expect from the driver.connection(parsedURI) above.

On Heroku I do only have the provided URI, but somehow getting the error. And since I do not get the user/password for db.authenticate(...) I have no idea how to deploy my app with ReactiveMongo on Heroku.

Hopefully there is some help.

**Comment by neilchaudhuri** [comment]
I am finding the error intermittently myself on Heroku. Weird.

**Comment by francisdb** [comment]
Same here, still breaks from time to time

**Comment by jamesallchin** [comment]
I consistently get this now - when using raw commands down to the on heroku (i'm using mongolab)

**Comment by francisdb** [comment]
@cchantep no comments?

**Comment by cchantep** [comment]
First this issue has been reported on the previous release, 7 months ago. Then the authentication has been refactored in 0.11. If there is any question about authentication with 0.11, this can be first discussed on the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo), and then possibly a new ticket for the current release could be raised with up-to-date details. Best regards.

**Comment by francisdb** [comment]
Seems indeed to be fixed :+1: 

```
2015-07-14T22:16:55.587129+00:00 app[web.1]: [info]    application        - ReactiveMongoApi starting...
2015-07-14T22:16:55.822182+00:00 app[web.1]: [info]    application        - ReactiveMongoApi successfully started with DB 'heroku_app00000'! Servers:
2015-07-14T22:16:55.822190+00:00 app[web.1]: 		[xxx.mongolab.com:0000]
```

**Comment by francisdb** [comment]
I take that back

using 0.11.2.play24
```java
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_app####.broadcasts' (code = 13)]
        at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32)
        at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:270)
        at reactivemongo.core.protocol.Response.error(protocol.scala:265)
        at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:479)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at reactivemongo.core.actors.LegacyDBSystem.aroundReceive(actors.scala:744)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cchantep** [comment]
Hi, having just deployed the [reactivemongo-demo-app](http://github.com/sgodbillon/reactivemongo-demo-app) on [Heruko](http://reactivemongo-demo-app.herokuapp.com/) with MongoLab, I don't see any error. I suggest you check your config, and authorized user on the configured database. Best regards.

P.S.: Please avoid posting duplicate message on several tickets.

**Comment by francisdb** [comment]
Excuses for the duplicate post. I will create a new issue with more info since both old issues are closed
