### ISSUE TITLE
Property duplication

### ISSUE THREAD

**Issue by kaygorodov** [ReactiveMongo/ReactiveMongo#225]
There is an incorrect possibility to have a BSONDocument  with two (or even more) same properties:

```
scala> (BSONDocument("name" -> "Initial Value") ++ BSONDocument("name" -> "Changed Value")).elements.toList
res14: List[reactivemongo.bson.BSONElement] = List((name,BSONString(Initial Value)), (name,BSONString(Changed Value)))
```

I am using the 0.10.5.0.akka23 version.
The reactivemongo driver even successfully inserts in the mongo instance such documents.
From the mongo console:

```
> db.users.find({})
{ "_id" : ObjectId("54832b6b148d380065a1c00d"), "name" : "Initial Value", "name" : "Changed Value"}
```

**Comment by cchantep** [comment]
Hi @kaygorodov , I'm not sure to understand why you say it's incorrect. MongoDB allows such document, so the drive behaves in the same way for me.

**Comment by kaygorodov** [comment]
Hi @cchantep, I checked the docs and it says that BSON format allows having such documents, but MongoDB process won't ever add duplicate fields.

From official docs:

BSON documents may have more than one field with the same name. Most MongoDB interfaces, however, represent MongoDB with a structure (e.g. a hash table) that does not support duplicate field names. If you need to manipulate documents that have more than one field with the same name, see the driver documentation for your driver.

Some documents created by internal MongoDB processes may have duplicate fields, but no MongoDB process will ever add duplicate fields to an existing user document.

http://docs.mongodb.org/manual/core/document/

**Comment by cchantep** [comment]
>From official docs:
>
>BSON documents may have more than one field with the same name.

So we agree that the DB itself allows it.

>Most MongoDB interfaces, however, represent MongoDB with a structure (e.g. a
>hash table) that does not support duplicate field names.

Most but not all :) (not a requirement as DB accepts it).

I think that if the most common case is to avoid such duplicate, then some config options or alternate document functions could be added, to keep both approaches.

**Comment by cchantep** [comment]
Close it for now. This can be discussed on the mailing list. If more feedback can be reopened.

**Comment by ymeymann** [comment]
We were also bitten by this. I agree that this is a MongoDB bug, not the driver's, but this behavior by MongoDB really sucks!
