### ISSUE TITLE
Missing implicit for org.joda.time.DateTime

### ISSUE THREAD

**Issue by lorehov** [ReactiveMongo/ReactiveMongo#242]
For example:
```
case class Task(
  _id: Option[BSONObjectID] = None,
  title: String,
  updated: Option[DateTime] = None,
) 

object Task extends Enumeration with MongoDao[Task] {
  import play.api.libs.concurrent.Execution.Implicits._
  implicit val ec = defaultContext

  private def db = ReactiveMongoPlugin.db
  def collection = db[BSONCollection]("tasks")
  implicit val handler = Macros.handler[Task]
}
```
will not compile as 
```
Error:(28, 40) Play 2 Compiler: 
 /Users/lorekhov/workspace/taskshot/app/models/Task.scala:28: Implicit org.joda.time.DateTime for 'value updated' not found
   implicit val handler = Macros.handler[Task]
```
Seems like it is a good idea - to add DateTime implicit in library :)

**Comment by reid-spencer** [comment]
It doesn't seem like a good idea to me. It implies that joda time is the way to do time. While I admit that that library is good, it isn't the only way to do it. Adding support for this in ReactiveMongo (RM) would require RM to depend on joda time and I'd rather have RM without such dependencies (despite that fact that I use joda time in my projects!). At most, RM ought to provide an implict for java.util.Date or other things that are part of the Java SDK, but not third party libraries.

**Comment by cchantep** [comment]
I agree with @reid-spencer . The support for Joda could be in a separate module, but having it in RM code would add a dependency to Joda for all projects using RM without Joda.

**Comment by lorehov** [comment]
Sorry, I just forgot to close an issue. (As I'm agree with @reid-spencer as well.)

**Comment by fehmicansaglam** [comment]
There is already an handler for joda DateTime in ReactiveMongo-Extensions: https://github.com/ReactiveMongo/ReactiveMongo-Extensions/blob/0.10.x/core%2Fsrc%2Fmain%2Fscala%2Fdao%2FHandlers.scala#L24
