### ISSUE TITLE
BSON.readOpt, writeOpt etc missing

### ISSUE THREAD

**Issue by eallik** [ReactiveMongo/ReactiveMongo#243]
Currently, in order to safely use `BSON.read[Foo](bson)`, one has to e.g. wrap it in `Try(...).toOption` or equivalent. Shouldn't there instead be `Option[T]` returning complements to `BSON.read`, `BSON.write` etc in `BSON`?

(Plug: by the way, why don't Readers and Writers rely on `readOpt` and `writeOpt` by default instead of the throw'y `read` and `write`?)

**Comment by eallik** [comment]
On fresh inspection, I realised that I can do `bson.asOpt[Foo]` which solves the problem. However, the question is, then, wouldn't it instead make sense to have `BSON.read(bson)` and `BSON.readOpt(bson)` as opposed to `BSON.read(bson)` and `bson.asOpt`?

**Comment by cchantep** [comment]
A shorthand `readOpt` could be added. Not sure it's worth the maintenance cost.

**Comment by yfinkelstein** [comment]
Pls see issue https://github.com/ReactiveMongo/ReactiveMongo/issues/320
that I just found. Using Try is a tremendous waste and is not warranted in many ordinary cases such as getKey where key does not exist. Can you give me one reason why asTry exists there in the first place? asOpt is just fine and is much more efficient.
