### ISSUE TITLE
Some operations are blocking and lock if using a global EC

### ISSUE THREAD

**Issue by aloiscochard** [ReactiveMongo/ReactiveMongo#244]
Hi,

I would have loved to investigate more, especially I would have love to know exactly what is going on.

But I unfortunately don't have time right now, so let me explain and hopefully you might have a reasonable explaination:

- If you try to call `BSONCollection.insert` using the global `ExecutionContext`, the operation **never** terminate.

From a wild guess, it feel like because something in ReactiveMongo is blocking... that is the only reason I see for this to happen (note that there is no problem by using an other EC), but I might be missing something.

I'm a bit surprised to see such issue with an async library, but to be clear I never had that issue when using read only commands.

Thanks for your help

Alois

**Comment by reid-spencer** [comment]
I use the global EC with collection inserts all the time without any issue. Could you show more of the code you're using to make the assertion you do? You do realize that it returns a future which will be satisfied asynchronously, right?

**Comment by aloiscochard** [comment]
@reid-spencer okay that's very good to hear!

I'll take time to have a minimal project reproducing the issue, now that you told me that I start to think the blocking is happening further down the stack, probably by **something else** than ReactiveMongo!

I'll keep you guys updated, thanks again.

**Comment by aloiscochard** [comment]
I close it for now, I was not able to reproduce this morning.

I think I was just being stupid (that happen often), sorry for the noise!
