### ISSUE TITLE
ReactiveMongo with MongoDB 2.8

### ISSUE THREAD

**Issue by bearrito** [ReactiveMongo/ReactiveMongo#246]
Are there any known issues with the ReactiveMongo driver and MongoDb 2.8?  

Should it work out of the box? If it should not is there a roadmap for getting there?

The improved concurrency story server side is a very important use case for us.

**Comment by cchantep** [comment]
I think you can get information for such question on the [Mailing List](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).
