### ISSUE TITLE
Loading files from GridFS is very CPU intense

### ISSUE THREAD

**Issue by tmbo** [ReactiveMongo/ReactiveMongo#25]
I am consuming the enumeratee returned from gridfs.find(...) with the following iteratee:

Iteratee.consume[Array[Byte]]()

This consuming is burning my cpu... Is there any way to retrieve the file as a whole? If not, there really needs to be one.

**Comment by tmbo** [comment]
@cchantep Did you find a way to fix it?

**Comment by cchantep** [comment]
This issue has been created in 2013. If reproduced with the latest 0.11.0 driver a new ticket can be created for this version. There is no plan to check it in previous releases for now. Best regards.
