### ISSUE TITLE
deserialization error for stats command

### ISSUE THREAD

**Issue by avdv** [ReactiveMongo/ReactiveMongo#263]
Originally reported here: ReactiveMongo/Play-ReactiveMongo#110

The MongoDB reply has a BSONDouble instead of the expected Int for the `totalIndexSize` property at 
[instanceadministration.scala line 74](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/commands/bson/instanceadministration.scala#L74)

**Comment by cchantep** [comment]
I see a similar issue (#277) but with `lastExtentSize` . Which MongoDB version is used in your case?

**Comment by avdv** [comment]
I'm using 2.6.7 currently.

Looking at the source of MongoDB (https://github.com/mongodb/mongo/blob/c809c0fd4668334ce39737ec9ff7de8d550a699f/src/mongo/db/dbcommands.cpp#L936), it becomes evident that the `stats` command has this kind of problem for almost any numerical entry of the return value.

That's because MongoDB uses the [appendNumber](https://github.com/mongodb/mongo/blob/7423c26ab95464a9b8f620ab4a11c297dc0621d5/src/mongo/bson/bsonobjbuilder.h#L260) function when appending numbers to the result document.

This function, depending on the value of the given `long long` parameter, decides whether to encode it as a BSONInt, BSONDouble or BSONLong using the following logic:

 * `value < 1073741824` => BSONInt
 * `value < 1099511627776` => BSONDouble
 * otherwise => BSONLong

So, IMO, the best option would be to choose a Long when decoding those values instead of a Double everywhere.

**Comment by cchantep** [comment]
@avdv The PR #277 has been merged in master. You can give a try to.
