### ISSUE TITLE
Constructed Update command is invalid

### ISSUE THREAD

**Issue by fehmicansaglam** [ReactiveMongo/ReactiveMongo#264]
When I try to make an update operation on a Mongo 2.6 server using ReactiveMongo 0.11, server returns the error below:

```
{
  ok: BSONDouble(0.0),
  errmsg: BSONString(wrong type for 'updates' field contents, expected object, found 4),
  code: BSONInteger(9)
}
```

If I am not mistaken the key name for update elements in an Update command should be `updates` but it is `documents` on the master branch: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/commands/rwcommands.scala#L196

**Comment by fehmicansaglam** [comment]
I was actually wrong. There error was slightly different. I have sent a PR.

**Comment by fehmicansaglam** [comment]
@sgodbillion could you merge this, if it is ok. It's blocking the development of ReactiveMongo Extensions.

**Comment by analytically** [comment]
+1
