### ISSUE TITLE
Write Concern not considered for insert for Mongo > 2.6 (default write concern is used)

### ISSUE THREAD

**Issue by wofr** [ReactiveMongo/ReactiveMongo#266]
If a MongoVersion > 2.6 is used the write concern is not used by the Insert command. The insert command will use the default write concern. 

  Failover2(db.connection, failoverStrategy) { () =>
      import MongoWireVersion._
      db.connection.metadata match {
        case Some(metadata) if metadata.maxWireVersion >= MongoWireVersion.V26 =>
          import reactivemongo.api.commands._
          runCommand(BatchCommands.InsertCommand.Insert(document)).flatMap { wr =>
            val flattened = wr.flatten
            if(!flattened.ok) // was ordered, with one doc => fail if has an error
              Future.failed(flattened)
            else Future.successful(wr)
          }

  object Insert {
    def apply(firstDoc: ImplicitlyDocumentProducer, otherDocs: ImplicitlyDocumentProducer*): Insert =
      apply()(firstDoc, otherDocs: _*)
    def apply(ordered: Boolean = true, writeConcern: WriteConcern = WriteConcern.Default)(firstDoc: ImplicitlyDocumentProducer, otherDocs: ImplicitlyDocumentProducer*): Insert =
      new Insert(firstDoc.produce #:: otherDocs.toStream.map(_.produce), ordered, writeConcern)
  }

**Comment by cchantep** [comment]
See #312
