### ISSUE TITLE
Collecting into an option

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#267]
I tried collecting a find into an Option but this gave me the following error:

```
...
  .collect[Option](1)
```

"Cannot construct a collection of type Option[play.api.libs.json.JsObject] with elements of type play.api.libs.json.JsObject based on a collection of type Option[_].
Error occurred in an application involving default arguments."

Would be nice if this would work and do something like
```
...
  .collect[List](1)
  .map(_.headOption)
```

(not sure if I should submit this to play-reactivemongo or here)

**Comment by cchantep** [comment]
I guess what you are looking for is [.headOption](http://reactivemongo.org/releases/0.10.5/api/index.html#reactivemongo.api.Cursor):

```scala
// cursor: reactivemongo.api.Cursor[JsObject]
val first: Future[Option[JsObject]] = cursor.headOption
```

**Comment by francisdb** [comment]
Duh, how could I miss that :-1:
