### ISSUE TITLE
play-json integration without play plugin

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#268]
Would be nice if you could release the play-json integration (JSONCollection) separately from the play plugin. Play-json is released separately and changes much less often.

My use case is using reactivemongo with play-json and akka-http

This would also open the door for other json library integrations.

**Comment by duncancrawford** [comment]
@francisdb we had the same requirement so did it ourselves and you can find it here https://github.com/hmrc/reactivemongo-json

**Comment by cchantep** [comment]
(Duplicate of https://github.com/ReactiveMongo/Play-ReactiveMongo/issues/103 )
