### ISSUE TITLE
Fongo for testing

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#269]
Just checking if anybody has ever tried to integrate with fongo for unit testing (https://github.com/fakemongo/fongo).

Would this be possible?
Would it be a lot of work to implement?

For reference this is a different solution which would fit more into the integration test category:
https://github.com/athieriot/specs2-embedmongo

**Comment by bfil** [comment]
I managed to use specs2-embedmongo in my unit tests quite easily, I'm using the following class: https://gist.github.com/bfil/2f82165851a053b3aba4

I haven't tried to integrate Fongo though

**Comment by cchantep** [comment]
Hi, although the [Google Google](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) may be a better place for such topic, I would add [Acolyte](http://acolyte.eu.org/reactive-mongo.html) as test tool.

**Comment by francisdb** [comment]
Agree, thanks for cleaning up

**Comment by ymeymann** [comment]
For those who find this issue on Google and are using latest reactive-mongo - I would not recommend Acolyte. See https://github.com/cchantep/acolyte/issues/30

**Comment by cchantep** [comment]
Acolyte now supports RM 0.11.9
