### ISSUE TITLE
Authentication attempts stop after the second one

### ISSUE THREAD

**Issue by vvlevykin** [ReactiveMongo/ReactiveMongo#282]
If the authentication fails, there is exactly one retry. Connection is left open, unauthenticated.

Steps to reproduce:
1. Connect with wrong credentials (for example, a user is not created yet)
2. MongoDBSystem stops authentication attempts
3. Create a user with these used credentials.

What is expected:
The following requests should be authenticated.

What happens:
DatabaseException['not authorized for query on ...' (code = 13)]

The issue was checked with:
* 0.10.5.0.akka23
* 0.11.0-SNAPSHOT

**Comment by cchantep** [comment]
Must be fixed by #408 (otherwise feedback welcome on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo))
