### ISSUE TITLE
Since 0.10.5 the KeepAlive value in the default MongoConnectionOptions differs from the default of StandardSocketOptions

### ISSUE THREAD

**Issue by wvandrunen** [ReactiveMongo/ReactiveMongo#300]
Since version 0.10.5 we ran into a lot of disconnected socket exceptions. When drilling into this problem we came to the following analysis:

Since the last version of ReactiveMongo the MongoConnectionOptions are used to configure the connection settings. 

In the default values of KeepAlive setting is set to true: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/api.scala#L481

In the previous version this settings has no default value set by ReactiveMongo. Then the connection falls back on the settings in the StandardSocketOptions: here the KeepAlive is set to false: http://docs.oracle.com/javase/7/docs/api/java/net/StandardSocketOptions.html#SO_KEEPALIVE

This setting is used for (from the documentation): _When the SO_KEEPALIVE option is enabled the operating system may use a keep-alive mechanism to periodically probe the other end of a connection when the connection is otherwise idle_.

The Mongo manual has this entry about KeepAlive: http://docs.mongodb.org/v2.6/faq/diagnostics/#does-tcp-keepalive-time-affect-sharded-clusters-and-replica-sets

This "new" behavior caused by giving a different default gave us a lot of weird socket disconnected errors; we are not using the OS keep-alive mechanism and therefore we haven't used the information from the Mongo documentation. When we override the KeepAlive default that is used in ReactiveMongo (true, where false should be the default) to the false, all our problems are gone.

The fix is easy; the default of KeepAlive should be the same as underlying frameworks that is uses (in this instance the standard StandardSocketOptions which is used by Netty for setting up SocketConnections.

Maybe this issues have something to do with the behavior described above? #162 #213

**Comment by cchantep** [comment]
A fix has been pushed to master
