### ISSUE TITLE
ReactiveMongo Sample Java Code

### ISSUE THREAD

**Issue by tru3d3v** [ReactiveMongo/ReactiveMongo#309]
Hi,

Do you have any sample ReactiveMongo with java language?

**Comment by fehmicansaglam** [comment]
ReactiveMongo is not compatible with Java. You may try Tepkin (https://github.com/fehmicansaglam/tepkin).

**Comment by tru3d3v** [comment]
Hi 
fehmicansaglam, Ok Thank You :)
