### ISSUE TITLE
Server status command

### ISSUE THREAD

**Issue by cchantep** [ReactiveMongo/ReactiveMongo#311]
Provides a command for `db.serverStatus()`.

Result of this command is [described in MongoDB](http://docs.mongodb.org/manual/reference/server-status/) documentation.
- [ ] locks
- [ ] opcounters
- [ ] opcountersRepl
- [ ] rangeDeleter
- [ ] repl
- [ ] security
- [ ] storageEngine
- [ ] wiredTiger

**Comment by mcveat** [comment]
I'm ready to put some work on it if no one started yet

**Comment by cchantep** [comment]
Hi @mcveat, a PR based on master about that is welcome. Do not hesitate +1

**Comment by cchantep** [comment]
```scala
import reactivemongo.api.commands.ServerStatus
import reactivemongo.api.commands.bson.BSONServerStatusImplicits._

db.runCommand(ServerStatus)
```

**Comment by cchantep** [comment]
Consider out of scope for now
