### ISSUE TITLE
BSONDocument.getTry(key:String) is VERY expensive if key not found

### ISSUE THREAD

**Issue by yfinkelstein** [ReactiveMongo/ReactiveMongo#320]
https://github.com/ReactiveMongo/ReactiveMongo/blob/master/bson/src/main/scala/types.scala#L60

```
 def getTry(key: String): Try[BSONValue] = Try {
    stream.find {
      case Success(element) => element._1 == key
      case Failure(e)       => throw e
    }.map(_.get._2).getOrElse(throw DocumentKeyNotFound(key))
  }
```

Note that getOrElse throws an exception with throw DocumentKeyNotFound(key)

This may be by design, but the problem with that is that it's very costly in JVM to create an instance og exception and fill its backtrace. I was doing CPU profiling and found that this particular line costs me 5% CPU just because I don't have an attribute in the document (which is optional in my case).

I love your API but I do not understand this particular design decision: why return Try instead of Option? it's in many other places in the driver. The key benefit of this parser is macro-based .as* converters and they all go through expensive asTry path (event though asOpt is also there )

**Comment by yfinkelstein** [comment]
Just to make sure: the issue is here is that throwing a new  exception just because the key is missing is too expensive.  If you must throw - throw a global exception instance constructed once. But consider that happens why I have an optional attribute in a bson document and map it to a scala field of type Option[String] for example. The current code with end up calling getTry () only to throw an exception and then discard it and set the scala field to None.

**Comment by yfinkelstein** [comment]
In my own version I did this:

```
// to avoid creating an exception every time there is no key
object DocumentKeyNotFound extends DocumentKeyNotFound ("key not found")

 def getTry(key: String): Try[BSONValue] = Try {
    stream.find {
      case Success(element) => element._1 == key
      case Failure(e)       => throw e
    }.map(_.get._2).getOrElse(throw DocumentKeyNotFound/*(key)*/)
  }
```
it's not elegant but effective.

**Comment by cchantep** [comment]
I don't think the getters with `Try` should be removed. That easily allows to mix values from RM and those from other `Try`, being said that `Option` can be used also.

Implementation can sure be improved.

**Comment by yfinkelstein** [comment]
>said that Option can be used also.
yes, but it goes through getTry / toOption which is too heavy. The macro implementation should invoke getOpt if the type is Option[_] rather than getTry. Do you agree?

**Comment by cchantep** [comment]
As said impl can be improved.
