### ISSUE TITLE
GenericCollection.remove doesn't honor firstMatchOnly for >= MongoWireVersion.V26

### ISSUE THREAD

**Issue by orElse** [ReactiveMongo/ReactiveMongo#322]
DeleteElement always uses 1 as limit, which translates to firstMatchOnly = true

def remove[T](query: T, writeConcern: WriteConcern = WriteConcern.Default, firstMatchOnly: Boolean = false)(implicit writer: pack.Writer[T], ec: ExecutionContext): Future[WriteResult] =
Failover2(db.connection, failoverStrategy) { () =>
db.connection.metadata match {
case Some(metadata) if metadata.maxWireVersion >= MongoWireVersion.V26 =>
import reactivemongo.api.commands._
import BatchCommands.DeleteCommand.{ Delete, DeleteElement }
runCommand(Delete(DeleteElement(query, 1))).flatMap { wr =>

**Comment by cchantep** [comment]
See #323
