### ISSUE TITLE
Ignore annotation functionality appears to be broken

### ISSUE THREAD

**Issue by yfinkelstein** [ReactiveMongo/ReactiveMongo#325]
@Ignore annotation is intended to skip case class parameters when generating reader and writer code using macros. I tried it an discovered that the logic is broken. What happens  is that the correspondence of parameter names and their types gets messed up. This is   evident from the following code in macros.scala:

```
    private def writeBodyConstructClass(A: c.Type): c.Tree = {
      val (constructor, deconstructor) = matchingApplyUnapply(A)
      val types = unapplyReturnTypes(deconstructor)
      val constructorParams = constructor.paramss.head

      val tuple = Ident(newTermName("tuple"))
      val (optional, required) = constructorParams.filterNot(ignoreField).zipWithIndex zip types partition (t => isOptionalType(t._2))
      val values = required map {
```

Note that filteredNot parameters are zipped with their types extracted before filtering!
Btw, there is no single unit test demonstrating @Ignore either.

**Comment by yfinkelstein** [comment]
This fix gets the job done:

```
      val (optional, required) = constructorParams.zipWithIndex zip types filterNot (tup => ignoreField(tup._1._1)) partition (t => isOptionalType(t._2))

```

**Comment by cchantep** [comment]
Hi @yfinkelstein , please attach a PR with the suggested modification.
