### ISSUE TITLE
Count command field property is not-documented

### ISSUE THREAD

**Issue by senz** [ReactiveMongo/ReactiveMongo#330]
[Count field](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/core/commands/commands.scala#L362) property is not officially supported, at least, I could not find it in [documentation](http://docs.mongodb.org/manual/reference/command/count/#dbcmd.count).

**Comment by cchantep** [comment]
Count operation is provided on collection in master: https://github.com/ReactiveMongo/ReactiveMongo/pull/317
