### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by duncancrawford** [ReactiveMongo/ReactiveMongo#331]
Please can you release a new version as I am unable to use snapahots in the environment I am working in.

Going forward it would be really useful for the community, and I would have thought make your lives easier too, if there were more regular release cycles.

**Comment by bfil** [comment]
I agree with @duncancrawford, it's been quite an unusual long time since the last release, and this project is being actively developed and maintained.

+1 for regular release cycles

**Comment by kyndainverse** [comment]
+1

**Comment by charleskubicek** [comment]
+1

**Comment by Roysvork** [comment]
+!

**Comment by haroonzone** [comment]
+1

**Comment by pomadchin** [comment]
+1

**Comment by luisobo** [comment]
afaik there is support for mongo 3.0 in master, there were some problems with index creation but it seemed to work with fine with the new storage engine. That is a big change for apps tho.

It would be great if we could have a way to test betas so we can provide feedback. Honestly, I don't know how that would look like in practice, but if it were as easy as change the reactivemongo version in my sbt to something like "2.0.0-beta1" I'd would start testing this right now. Maybe it'd be just a matter of documenting something among these lines in the README. I'd be happy to help if pointed in the right direction.

Something like this would reduce the pressure to release a new version (people could get access to features via this channel) while the maintainers would still get feedback from real world usage.

**Comment by bfil** [comment]
The latest published snapshot in OSS is from October 2014, it would definitely be useful to, at least, publish the snapshots regularly (suggested here: https://github.com/ReactiveMongo/ReactiveMongo/issues/306)

It would also enable a faster feedback loop from the ReactiveMongo community.

**Comment by duncancrawford** [comment]
@sgodbillon it would be great to have your views on this topic

**Comment by duncancrawford** [comment]
In the meantime, I have forked master and published some release candidates (equivalent to -SNAPSHOTS in Nexus) to bintray.

The three artefacts are here:
https://bintray.com/hmrc/release-candidates/reactivemongo
https://bintray.com/hmrc/release-candidates/reactivemongo-bson
https://bintray.com/hmrc/release-candidates/reactivemongo-bson-macros

The release candidate version is 0.10.0-132-gbbee704

The format being lastGitHubTag-theNumberOfCommits-lastCommit

If you would like to use these then add the following to your resolvers:

```
Resolver.bintrayRepo("hmrc", "release-candidates")
```

Next week I will release a version

**Comment by bfil** [comment]
I've ended up forking and pushing it to my nexus repository as well for the time being.

Good news is that everything looks like working fine without touching a single line of code, I thought it could be a tricky update after 8 months of unreleased updates.

**Comment by cchantep** [comment]
A [topic on the MailingList](https://groups.google.com/forum/m/?fromgroups#!topic/reactivemongo/gC5vLErbq8E) is indicating where a more recent snapshot can be found.

I'd like to add the maintainers of ReactiveMongo are all volunteers, and also have manage other obligations.

**Comment by bfil** [comment]
Already tried Tatami's repo but it does not work well, as I've pointed out in [this mailing list discussion](https://groups.google.com/d/msg/reactivemongo/Fffuu2TL0Lk/jFv5I6li_3wJ).

**Comment by cchantep** [comment]
What's is the issue ?

**Comment by bfil** [comment]
The [metadata](https://github.com/cchantep/tatami/blob/master/snapshots/org/reactivemongo/reactivemongo_2.11/0.11.0-SNAPSHOT/maven-metadata.xml) does not match the versions in the folder, it tries to download `reactivemongo_2.11-0.11.0-20150430.224124-6.pom` but in the folder [as you can see here](https://github.com/cchantep/tatami/tree/master/snapshots/org/reactivemongo/reactivemongo_2.11/0.11.0-SNAPSHOT) the latest one is `reactivemongo_2.11-0.11.0-20150430.201612-4.pom`

**Comment by cchantep** [comment]
Thanks for reporting that. Please try again now.

**Comment by bfil** [comment]
Looks good now, thanks. Is there any particular reason why the new snapshots are not being published to Sonatype?

**Comment by duncancrawford** [comment]
Hi all, we have released a version and the details of the fork can be found here https://github.com/hmrc/ReactiveMongo#reactivemongo-fork-details

**Comment by cchantep** [comment]
A review of pending PR will be done this week to publish consolidated snapshots.

**Comment by cchantep** [comment]
The milestone of the driver is now published on the Maven central repository as `"org.reactivemongo" %% "reactivemongo" % "0.11.0-M2"`. It will be released as final 0.11.0 by end this week.
