### ISSUE TITLE
mongo-java-driver-reactivestreams

### ISSUE THREAD

**Issue by francisdb** [ReactiveMongo/ReactiveMongo#333]
I was wondering if using the mongo reactive java driver as a backend might be a good idea.
http://mongodb.github.io/mongo-java-driver-reactivestreams/

Since this is an official driver I suppose it won't have issues like #224

ps: can the project have a gitter chat to discuss such topics?

**Comment by bfil** [comment]
I was wondering the same thing, it looks like they already have a placeholder for a Scala Reactive Streams driver as well https://github.com/mongodb/mongo-scala-driver-reactivestreams

**Comment by cchantep** [comment]
Depending on this driver is not planed (for the same reason ReactiveMongo was created on the base of the Java driver). Such discussion can take place on the [Mailing List](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo). Best regards.

**Comment by ymeymann** [comment]
@cchantep What about https://github.com/mongodb/mongo-scala-driver (or the underlying https://github.com/mongodb/mongo-java-driver/tree/master/driver-async) - does the above answer still hold?

**Comment by cchantep** [comment]
Yes. ReactiveMongo doesn't depend on any other driver (and doesn't plan to).
