### ISSUE TITLE
Call MongoDB function to generate field value on insert

### ISSUE THREAD

**Issue by nykolaslima** [ReactiveMongo/ReactiveMongo#348]
I have some legacy need to keep an auto increment field into my MongoDB collection.
I followed MongoDB's tutorial on how to do it: http://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/

Now, in my project's code I need to call this function when inserting a document into MongoDB with ReactiveMongo.

```
implicit object DevelopmentWriter extends BSONDocumentWriter[Development] {
    override def write(t: Development) = BSONDocument(
      "id" -> t.id,
      ...
      )
  }
```
how can I change this implicit converter to use the `id` attribute when it's not None and to use the function when it's None?

**Comment by cchantep** [comment]
You can add an `Option[BSONObjectId]` for `_id` in your writer. Let it `None` when you want auto-generation, put `Some(id)` when you want an explicit id.

If you have other question, please use the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), rather than this issue tracker.

Best regards.

**Comment by nykolaslima** [comment]
@cchantep thank you for your response.

I don't want to change `_id` behaviour. I want another new field called `id`.
Besides that, I can't set an explicit `id` value because it's calculated by a MongoDB function. I need to call this function to get the ID value.
How can I call MongoDB functions with ReactiveMongo?

**Comment by nykolaslima** [comment]
@cchantep I found the solution.
We could use `BSONJavascript` in order to call the function:
```
implicit object DevelopmentWriter extends BSONDocumentWriter[Development] {
    override def write(t: Development) = BSONDocument(
        "id" -> t.id match {
          case Some(id) => "id" -> t.id
          case None => "id" -> BSONJavaScript("getNextSequence(\"counterId\")")
        },
        ....
        )
  }
```

**Comment by cchantep** [comment]
You can either try `BSONJavaScript` or use the `BSONObjectID.generate`.

Please consider using the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) for such discussion. This tracker is dedicated to confirmed issue.

Best regards

**Comment by nykolaslima** [comment]
I posted the solution above. Thank you for your help @cchantep and I'm sorry for this issue.
:tada:

**Comment by priyatham42** [comment]
![error](https://cloud.githubusercontent.com/assets/8111238/12291287/5c79d376-ba0c-11e5-9f26-c7870af277f0.png)

card_id is my auto_increment field, I'm trying to use BSONJavaScript to call mongodb function in my writes, but doesn't work, saying 'unhandled json value'.
Where am I doing wrong?

**Comment by cchantep** [comment]
Hi @priyatham42 , please first ask question on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), rather than on this issue tracker (and please paste code rather than limited screenshot). best regards.
