### ISSUE TITLE
List all collection elements without need to create empty BSONDocument

### ISSUE THREAD

**Issue by nykolaslima** [ReactiveMongo/ReactiveMongo#350]
When we want to list all elements in a collection, we can do it this way:
`carCollection.find(BSONDocument()).cursor[Car].collect[List]()`

But this `BSONDocument()` seems "unnecessary". It would be better if we could do:
`carCollection.find().cursor[Car].collect[List]()`

But this code get broke because we don't have a implicit `Writer` for `Unit`.
I was thinking about add a `implicit Writer[Unit]` that maps to `Writer[BSONDocument]`. 
What do you guys think about it? With this approach we could get a cleaner syntax.

**Comment by cchantep** [comment]
Hi,

Please first discuss such feature request on the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo). In any case, as this is an edge case with an quite easy workaround, any improvement would be low priority. 

Best regards

**Comment by nykolaslima** [comment]
Hello @cchantep 
Since it's a easy workaround, wouldn't be easier to quickly discuss if it worth or not?

**Comment by cchantep** [comment]
It can be discussed on the mailinglist.
