### ISSUE TITLE
BSONObjectID.generate may require the processid too?

### ISSUE THREAD

**Issue by labe-me** [ReactiveMongo/ReactiveMongo#369]
Hello and thank you for ReactiveMongo !

Currently the code and doc rightly state that BSONObjectID.generate uses:

timestamp (in seconds) + machine identifier + thread identifier + increment

I somewhat expected to have the system process id included in the mix too.

Am I right to fear a higher risk of collision with multiple JVM running on the same server?

Best regards
Laurent

**Comment by cchantep** [comment]
Hi, thanks for your feedback, and to use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) for such discussion, rather than this issue tracker. Best regards.
