### ISSUE TITLE
Question: is this BSON handler enhancment worth being contributed back to Reactive Mongo?

### ISSUE THREAD

**Issue by kailuowang** [ReactiveMongo/ReactiveMongo#397]
https://github.com/A-Noctua/shifu/blob/master/backend/src/main/scala/com/iheart/shifu/repo/GeneralHandlers.scala

There are several features provided in this file but the main reason I am asking this question here is the following one:  it allows you to compose handlers with fields like the play json lib. This allows you to avoid writing the same logic twice in a writer and reader, which is sometimes required when 
a) you want to use different field names than the name in the case class, or
b) the macro doesn't work for your case class which has type parameters. 

Here is an example:

``` 
import play.api.libs.functional._
import com.iheart.shifu.repo.GeneralHandlers._ 

// note that in GeneralHandler I have a type Handler[T] = BSONDocumentReader[T] with BSONDocumentWriter[T]

case class Student(name: String,  age: Int, height: Double)

  implicit val sh: Handler[Student] =
    ( field[String]("n") ~
      field[Int]("a") ~
      field[Double]("h"))(Student.apply, unlift(Student.unapply))

```

Let me know if you guys are interested in seeing it in a PR. But it will need a small dependency  "com.typesafe.play" %% "play-functional" % "2.3+"

**Comment by cchantep** [comment]
Hi @kailuowang , thanks for your interest in ReactiveMongo.

For any feature suggestion, please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), rather than this issue tracker.

Best regards,

> P.S. You can already using Play JSON function to define JSON handlers, which can than be used for ReactiveMongo JSON serialization provided by the [Play module](http://github.com/reactivemongo/play-reactivemongo).
