### ISSUE TITLE
ConnectionNoteInitialized / Spray.io

### ISSUE THREAD

**Issue by levelvc** [ReactiveMongo/ReactiveMongo#400]
Getting the following error within Spray.io spray-can:

ERROR reactivemongo.api.Failover2 - Got an error, no more attempts to do. Completing with a failure...
reactivemongo.core.errors.ConnectionNotInitialized: MongoError['Connection is missing metadata (like protocol version, etc.) The connection pool is probably being initialized.']

The ReactiveMongo Driver works properly if I call it from Scala sbt console. 

Here is the code:

  val system = ActorSystem("freestyle", ConfigFactory.load.getConfig("akka"))

  val logger = Logging.getLogger(system, getClass())

  val driver = new MongoDriver(Some(system.settings.config))
  val connection = driver.connection(List("10.0.0.55"))
  val db = connection("dbname")

**Comment by cchantep** [comment]
Hi, please use the [user MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask question, rather than this issue tracker. Best regards.
