### ISSUE TITLE
Sealed families of case classes support

### ISSUE THREAD

**Issue by julienrf** [ReactiveMongo/ReactiveMongo#407]
The current macros do not support sealed families of case classes, so you can not write the following:

~~~ scala
sealed trait Event
case class Foo(s: String) extends Event
case class Bar(i: Int) extends Event

object Event {
  implicit val handler: BSONHandler[BSONDocument, Event] = Macros.handler[Event]
}
~~~

**Comment by cchantep** [comment]
I guess a PR can be done, based on [your lib](https://github.com/julienrf/reactivemongo-derived-codecs).

**Comment by julienrf** [comment]
Are you ok to add a dependency on shapeless?

**Comment by cchantep** [comment]
It may be nice if we can lessen the dependency, but for shapeless is ok for me. The `[BSONDocumentHandler](https://github.com/julienrf/reactivemongo-derived-codecs/blob/master/src/main/scala/julienrf/bson/BSONDocumentHandler.scala) could be added in the BSON module, and the shapeless codec in the BSON macros (which is planned for a full refactoring).

**Comment by julienrf** [comment]
What is precisely planned in this refactoring?

**Comment by cchantep** [comment]
The macros are quite old, until now I haven't had time to refactor it.
