### ISSUE TITLE
[Question] Obtain DefaultDb instance while using URI as connection parameter

### ISSUE THREAD

**Issue by stremlenye** [ReactiveMongo/ReactiveMongo#410]
Hi,
I want to use mongo URI like `mongodb://localhost:27017/db_name` to construct `MongoConnection` object like it shown in [docs](http://reactivemongo.org/releases/0.11/documentation/tutorial/connect-database.html)
```scala
val driver = new MongoDriver
MongoConnection.parseURI(uri)
  .map(parsedUri => driver.connection(parsedUri)).get
```
Is it possible to retrieve the `DefaultDB` object out of the connection object without specifying db name explicitly as far as far as it already presented in the URI?

Now I am doing it in that way: 
```scala
val driver = new MongoDriver
MongoConnection.parseURI(uri)
  .map(parsedUri => driver.connection(parsedUri))
  .map(connection => connection.db("db_name")).get
```

**Comment by cchantep** [comment]
Hi, please use the [user MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question (this tracker is for confirmed issue). Best regards.

P.S.: When moving it to the MailingList, please be more specific, as I don't see your problem there.
