### ISSUE TITLE
Website scrolling issue

### ISSUE THREAD

**Issue by solix** [ReactiveMongo/ReactiveMongo#412]
Hi, I was reading documentation at http://reactivemongo.org/...  using my android mobile and It seems there is some issue with scrolling down the page, mainly the page is not scrolable at all. Also tested on firefox desktop version when resizing the window to half, the same issue persists!

**Comment by UriShohet** [comment]
Same here, on Nexus 5, switching to the desktop site in Chrome doesn't help either.
