### ISSUE TITLE
aggregation problem

### ISSUE THREAD

**Issue by yadid** [ReactiveMongo/ReactiveMongo#413]
Hi,

Im having issues with submitting an aggregation via the RawCommand api.
the returned result was too large, so I added "cursor"->BSONDocument("batchSize"->1) to the aggregation command.
The command succeeds, but I have no idea how to access the returned cursor.
Before adding the cursor to the aggregation I could access the result like so:

val futureDoc = db.command(RawCommand(doc))
val res =  Await.result(futureDoc,10.seconds)
val items = (res.getAs[List[MyClass]]("result") getOrElse List())

But obviously that does not work anymore. 
Any ideas on how to achieve this ?

**Comment by cchantep** [comment]
Hi, please use the [MaillingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask for help/question. Best regards.

> You can have a look at the [aggregation doc](http://reactivemongo.org/releases/0.11/documentation/advanced-topics/aggregation.html).
