### ISSUE TITLE
ReactiveMongo 0.11.7 with Play 2.3.10

### ISSUE THREAD

**Issue by YannMoisan** [ReactiveMongo/ReactiveMongo#414]
Is it supported ?
It seems to broke everything on my project…

Nevertheless, there is a version of the plugin for play 2.3. (0.11.7.play23)…

**Comment by cchantep** [comment]
Hi, please use to the [mailing list](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo). This tracker is for confirmed issues. Best regards.
