### ISSUE TITLE
Document MongoDB version compatibility

### ISSUE THREAD

**Issue by danmassie** [ReactiveMongo/ReactiveMongo#416]
Document which versions of ReactiveMongo are compatible with which versions of MongoDB.

**Comment by cchantep** [comment]
Please look at the [documentation](http://reactivemongo.org/releases/0.11/documentation/release-details.html), or use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question.

**Comment by danmassie** [comment]
Apart from the latest release there is no indication on any previous release notes or documentation as to which versions of mongo they can be used with. It would therefore be helpful to users to have this noted somewhere in the documentation.

**Comment by cchantep** [comment]
Please @danmassie be constructive and read the doc:

> MongoDB versions older than 2.6 are not longer supported by ReactiveMongo

**Comment by mickaeltr** [comment]
Hello,
Could someone let met know where I can find MongoDB compatibility with 0.18 and 0.19 ReactiveMongo drivers?
Thanks

**Comment by mickaeltr** [comment]
I found out in the mailing list that MongoDB 4.2 is supported since ReactiveMongo 0.18.5
https://groups.google.com/g/reactivemongo/c/7gK6mNpiVoY/m/TRAiGEpbAwAJ
