### ISSUE TITLE
Can't import reactivemongo after a successful build

### ISSUE THREAD

**Issue by mutazmq** [ReactiveMongo/ReactiveMongo#418]
I add this to my libraryDependencies
    
    "org.reactivemongo" %% "play2-reactivemongo" % "0.11.7.play24"

But after clean compile, eclipse still shows "Not found: Object reactivemongo". Also play2-reactivemongo_2.11-0.11.7.play24 is not added to my referenced libraries.  So if I add this line to my model file, play app will give compilation error:

    import reactivemongo.bson.BSONDocument

Any idea what is going wrong?

**Comment by cchantep** [comment]
Hi, please use the MailingList to ask question. Best regards.

**Comment by yuchaosydney** [comment]
Hi, can I ask what is MailingList? I got the same issue here.

**Comment by cchantep** [comment]
The MaingList must be used to ask for question/for help.
