### ISSUE TITLE
Authorization Issues Connecting to MongoDB 3.0

### ISSUE THREAD

**Issue by joesan** [ReactiveMongo/ReactiveMongo#419]
I'm having some problems connecting to a MongoDB database running version 3.0!

CommandError[code=13, errmsg=not authorized on myDb to execute command { insert: "user", documents: [ { .....},
  code: BSONInteger(13)
}]

Is this some incompatibility issue? This is just bugging me! I have written lots of code for the persistence and now the very basic connection seems to be problematic is really scaring me.

**Comment by cchantep** [comment]
Hi, please read the [documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/connect-database.html) (and have a look at `authMode`) and/or use the [mailinglist](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask questions. Best regards.

**Comment by joesan** [comment]
I did try all possibilities and it seems like the problem is definitely in the ReactiveMongo library. I did try to log in using the command line with exactly the same credentials to the MongoLab instance and I was able to insert the entry into my collection! Here is the URL that I tried (with the auth mode):

mongodb://user:pass@XXXXX.mongolab.com:XXXXX/myDbName?authMode=scram-sha1

**Comment by cchantep** [comment]
Hi, if you look at the [MailingList](https://groups.google.com/d/msg/reactivemongo/x3OZ6-hIIXk/XCj99_yyCAAJ), you can see that a demo app using MongoLab is successfully working at Heroku.

Please check your env and use the MailingList for further discussion. Best regards.
