### ISSUE TITLE
Creating/ensuring indexes doesn't fail with an exception

### ISSUE THREAD

**Issue by tjjalava** [ReactiveMongo/ReactiveMongo#421]
I was trying to ensure an unique index on a collection that had duplicates and noticed, that `CollectionIndexesManager.ensure` returned `true` even though the actual index wasn't created. It seems that ensure relies on `CollectionIndexesManager.create` to fail, otherwise it just maps the `WriteResult` to boolean ([indexes.scala](https://github.com/ReactiveMongo/ReactiveMongo/blob/0.11.7/driver/src/main/scala/api/indexes.scala#L394)). I tried with `create` and it indeed returns a successful future of `WriteResult` that has `ok = false`. I'm not sure if the `create` should return a failed future or not, but at least `ensure` won't signal in any way if the index creation failed.

Here's what I tried:
```scala
val indexesManager = api.db.collection[BSONCollection]("accounts").indexesManager
val index = Index(Seq("email" -> IndexType.Ascending), unique = true)

indexesManager.create(index).map { wr =>
  println(wr.ok)
  println(wr.errmsg.get) 
}

indexesManager.ensure(index).map(println)
```

Output:
> false
> exception: E11000 duplicate key error index: refactor.accounts.$email_1 dup key: { : "test@example.org" }
> true

I'm using ReactiveMongo 0.11.7 with Play 2.4 and play2-reactivemongo 0.11.7.play24.

**Comment by cchantep** [comment]
Hi, `.ensure` doesn't rely on `.create` to [check whether the index already exists](https://github.com/ReactiveMongo/ReactiveMongo/blob/0.11.7/driver/src/main/scala/api/indexes.scala#L393). Please first move this discussion on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), giving more details about the collection and indexes, before raising a ticket on this tracker. Best regards.
