### ISSUE TITLE
Connection corruption leads to stuck requests

### ISSUE THREAD

**Issue by chemikadze** [ReactiveMongo/ReactiveMongo#435]
We have a tricky situation with reactivemongo that looks like that driver gets stuck and stops handling requests, which leads to mongodb result futures not to complete either with write results or exceptions.

Symptoms are the following:
 - MongoDBSystem.awaitingResponses has hundreds of elements
 - all stuck operations are scheduled on same connection
 - we have live cursor of query operation on this connection with big amount of results run against collection, which have read only single batch of data

One of theories, is that connection may die or something and driver just did not noticed that fact somehow or [https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/core/actors.scala#L349](is ignoring further writing results) to dead connection.

Do anyone have any ideas about that?

**Comment by cchantep** [comment]
Hi, this tracker is dedicated to confirmed issue. Please first ask on the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) (indicating which version you are using + details about the use case). Best regards.
