### ISSUE TITLE
FieldPath field names may not start with '$'

### ISSUE THREAD

**Issue by agugaillard** [ReactiveMongo/ReactiveMongo#440]
Knowing that this code will work properly:
```javascript
db.foo.aggregate(
  {
    "$match": {
      "_id": ObjectId("5689943aef070007088d93a9")
    }
  },
  {
    "$unwind": "$bars"
  },
  {
    "$project": {
      "_id": "$bars._id",
      "name": "$bars.name"
    }
  }
)
```

This should also work:
```scala
import fooCollection.BatchCommands.AggregationFramework.{ Match, Project, Unwind }
fooCollection.aggregate(
  Match(Q.get(id)),
  List(
    Unwind("$bars"),
    Project(BSONDocument(
      "_id" -> "$bars._id",
      "name" -> "$bars.name")))).map { r => r.result[Bar] }
```

But it throws: **FieldPath field names may not start with '$'**.

I workarounded it by changing:
```scala
Unwind("$bars")
// ->
Unwind("bars")
```

The javascript code doesn't work if I apply the same change.

**Comment by cchantep** [comment]
Hi, please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask questions.

> The field path is automatically prefix with `$` by the stage `Unwind` in ReactiveMongo API.
