### ISSUE TITLE
Erroneous Regex Query Rewriting

### ISSUE THREAD

**Issue by NTCoding** [ReactiveMongo/ReactiveMongo#449]
For a query like this:

`BSONDocument("keywords" -> BSONDocument("$elemMatch" -> BSONDocument("$regex" -> term)))`

It is being mangled and sent to mongo like this:

` [conn25] assertion 17287 Can't canonicalize query: BadValue $elemMatch needs an Object ns:rentreg.entries query:{ $query: { keywords: { $elemMatch: /Lond/ } }, $readPreference: { mode: "nearest" } `

For some reason the $regex document is being completely stripped out. Doesn't happen if I change $regex to another command like $eq.

I have tried constructing the query using Play Json's Json.obj syntax, but still the same problem.

**Comment by cchantep** [comment]
Hi,

You should use `BSONRegex` (see [documentation](http://reactivemongo.org/releases/0.11/api/index.html#reactivemongo.bson.package)).

Please first ask on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo), rather than on this issue tracker.

Best regards.
