### ISSUE TITLE
BulkWrite op (3.2)

### ISSUE THREAD

**Issue by cchantep** [ReactiveMongo/ReactiveMongo#473]
https://docs.mongodb.org/manual/core/bulk-write-operations/

**Comment by mcastellini** [comment]
This issue is the only one that I found mentioning bulk writes in ReactiveMongo. Has it been implemented or are there any plans to implement it?

**Comment by cchantep** [comment]
There is no MongoDB bulkWrite command, that's MongoShell features, so don't fit well the driver well. The existing bulkInsert operation will be refactored (no specific planning). BTW the place to ask question is rather the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) (as this tracker is for confirmed issue or actionable feature request). Best regards
