### ISSUE TITLE
Update to Netty 4.x

### ISSUE THREAD

**Issue by cchantep** [ReactiveMongo/ReactiveMongo#500]
http://netty.io/wiki/new-and-noteworthy-in-4.0.html

**Comment by mavarazy** [comment]
+1 (Waiting for update to switch to Play 2.5.x)

**Comment by cchantep** [comment]
That's not related to Play.

**Comment by mavarazy** [comment]
Play 2.5.x uses Netty 4.x, and ReactiveMongo uses Netty 3.x
Netty changed package naming in 4.x so effectively I can have both Netty 3.x & 4.x as dependencies.
To avoid that I downgraded to Play 2.4.x

**Comment by cchantep** [comment]
There is no issue having both
