### ISSUE TITLE
upgrade to akka 2.4 / play 2.5

### ISSUE THREAD

**Issue by joprice** [ReactiveMongo/ReactiveMongo#520]
Will an upcoming version of ReactiveMongo support akka 2.4 and play 2.5?

**Comment by akitaylor** [comment]
ReactiveMongo already supports play 2.5 since version 0.11.11 (the latest version is 0.11.13).

**Comment by cchantep** [comment]
Hi, as indicated, this tracker is for confirmed issue or actionable request. The [MailingList](

**Comment by cchantep** [comment]
Test coverage from [Akka 2.3.13 up to 2.4.8](https://github.com/ReactiveMongo/ReactiveMongo/pull/531/files#diff-354f30a63fb0907d4ad57269548329e3R26)
