### ISSUE TITLE
Looking to query nested bSONs not working

### ISSUE THREAD

**Issue by PeeyushAgg** [ReactiveMongo/ReactiveMongo#535]
I had a document with _id as 
```
_id : {
       field1 : value2,
       field1 : value2
      }
```

I tried to query if in find method as 

```
BSONDocument("_id" -> BSONDocument("field1" -> value1, "field2" -> value2))
```

The operator was completed with a null list. 

please help

**Comment by cchantep** [comment]
Hi, this tracker is for confirmed issue. Please first use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask for help. Best regards.
