### ISSUE TITLE
Kamon monitoring

### ISSUE THREAD

**Issue by cchantep** [ReactiveMongo/ReactiveMongo#556]

**Comment by jtjeferreira** [comment]
@cchantep I worked on an integration library for kamon 1.0. You can find it in https://github.com/jtjeferreira/kamon-mongo. Currently it is just producing traces, but should be easy to produce metrics...

**Comment by cchantep** [comment]
Interesting. Have you had a chance to look at the JMX implementation and the way it's bound to polls?

**Comment by jtjeferreira** [comment]
Not really. I was more interested in generating traces, so that I could send them to zipkin or jaeger...
