### ISSUE TITLE
WriteResults.originalDocument public API but not implemented

### ISSUE THREAD

**Issue by JakubDziworski** [ReactiveMongo/ReactiveMongo#582]
I used this method but turns out it is not implemented:
https://github.com/ReactiveMongo/ReactiveMongo/blob/f7da2d9901806883666f9645a27649595c8b24b1/driver/src/main/scala/api/commands/writeresult.scala#L28

DefaultWriteResult does not override it either so I always get same empty result

**Comment by cchantep** [comment]
Hi, this legacy is kept (useless) for binary backward compat, but will probably be removed. The error details are available as `code` and `errmsg`. Best regards.

> Please use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask question or for help, this tracker is for confirmed issue/actionable request.
