### ISSUE TITLE
Default read preference "secondary" breaks write commands

### ISSUE THREAD

**Issue by fedenusy** [ReactiveMongo/ReactiveMongo#603]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)

0.12.0

### MongoDB version (2.6, 3.0 / etc)

3.2

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Reproduced on:

 Mac OS X El Capitan - `15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64`

And:

The `openjdk:8-jre` Docker container - `Linux 2964313-x8199 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux`

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Mac JVM:

```
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

Docker container JVM:

```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

### Library Dependencies

Akka 2.4.10

### Expected Behavior

All write commands should go to the Primary node.

### Actual Behavior

After booting the reactivemongo driver with default `readPreference` set to `secondary` or `secondaryPreferred`, all writes go to secondary nodes. Any `update` operation therefore returns an error:

```
res11: scala.concurrent.Future[reactivemongo.api.commands.UpdateWriteResult] =
Failure(reactivemongo.api.commands.bson.DefaultBSONCommandError: CommandError[code=10107, errmsg=not master, doc: {
  ok: BSONDouble(0.0),
  errmsg: "not master",
  code: BSONInteger(10107)
}])
```

### Reproducible Test Case

I'm not very familiar with reactivemongo yet, so I'll let the maintainers come up with an appropriate test & solution.

~~After taking a brief look, it seems like the culprit might be `genericcollection.scala`. In that file, it looks like `update`, `findAndModify`, `remove`, and `insert` all issue commands using the default read preference. The issue might be solved by updating those methods to issue writes with `ReadPreference.Primary`.~~

Maintainers may also want to refactor this internal API, since "read preference" should play no role in write commands.

**Comment by cchantep** [comment]
Hi,

Have you tried `.withReadPreference(primary)` on the collection before executing the write operations?

> Note that the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) is available for preliminary discussion.

Best regards

**Comment by fedenusy** [comment]
No, I haven't. I ended up setting default read preference = "primary" for now. 

While this issue's open, I'll specify read preference = "secondary" on most read commands. That seems more intuitive than saying write commands should run .withReadPreference(primary).

I decided to skip the mailing list since this is clearly a bug. If you'd prefer me to move this discussion to the mailing list, I'm happy to open a thread :)

**Comment by cchantep** [comment]
That's always better to go through discussion first, what's the only way to qualify it's "clearly a bug".

**Comment by fedenusy** [comment]
Ok sure. I'm going off my experience with 3 other Mongo drivers (ruby, python, and java). Each allows you to set default read preference, and writes still work. 

Are you saying that you'd expect default read preference = "secondary" to break all writes?
