### ISSUE TITLE
Provide non-deprecated way to iterate over aggregation cursor

### ISSUE THREAD

**Issue by danslapman** [ReactiveMongo/ReactiveMongo#608]
Currently `enumerate` method is deprecated in a favor of `enumerator` from play-iterateess. However, methods like `aggregate`, `aggregate1` returns legacy `Cursor[T]` and there is no way to call `enumerator()` on them. This is very inconvenient because it forces to disable '-Xfatal-warnings'

**Comment by cchantep** [comment]
Hi @danslapman , as [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help) the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) is the place to ask question/for help.
