### ISSUE TITLE
Very poor performance on Cursor collect method

### ISSUE THREAD

**Issue by nodarret** [ReactiveMongo/ReactiveMongo#613]
Collecting lots of documents using method collect without specyfing maxDocs param or using default -1 value results very poor performance compared to maxDocs = Int.MaxValue.

**For example i have collection with 170448 documents.**
When i try collect keys using code 
`cursor.collect[List](200000)` or `cursor.collect[List](Int.MaxValue)`
it results with two responses in ~1s:
```
Reply(8,223966448427,0,127100)
Reply(8,0,127100,43348)
```
When i try collect using code `cursor.collect[List]()` or `cursor.collect[List](-1)`
it results with 43348 responses in ~50s:
```
Reply(8,225563856273,0,127100)
Reply(8,225563856273,127101,1)
Reply(8,225563856273,127102,1
[...]
Reply(8,225563856273,170447,1)
```

Problem is with this code in method next when maxDocs<0:
```scala
val toReturn =
   if (numberToReturn > 0) numberToReturn
   else maxDocs - (
      response.reply.numberReturned + response.reply.startingFrom
   )
```
When maxDocs=-1 results with negative toReturn values, for example: 
`[Cursor] Calling next on 226784333516, op=GetMore(cfa_perf.personrule,-127101,225563856273)`
Negative values in toReturn parameter results with one document returned.

I think next method shoiuld have same code check on maxDocs like makeRequest method:
````scala
val nrt = query.numberToReturn
val max = if (maxDocs < 0) Int.MaxValue else maxDocs
val q = { // normalize the number of docs to return
  if (nrt > 0 && nrt <= max) query
  else query.copy(numberToReturn = max)
````

### MongoDB version (3.2.9)

**Comment by cchantep** [comment]
@nodarret you can try with the 1.2.1-SNAPSHOT
