### ISSUE TITLE
reactivemongo 0.12.1 breaks projects using play 2.5.x

### ISSUE THREAD

**Issue by leckardt** [ReactiveMongo/ReactiveMongo#616]
reactivemongo 0.12.1 introduces a dependency on play-iteratees 2.6.1, where version 0.12.0 only required 2.3.10, and thus breaking play at runtime when Streams are used:

>java.lang.NoClassDefFoundError: play/api/libs/concurrent/StateMachine
>java.lang.NoClassDefFoundError: play/api/libs/streams/impl/EnumeratorSubscription

I tried pinning the play-iteratees module to 2.5.10:
>dependencyOverrides += "com.typesafe.play" %% "play-iteratees" % "2.5.10"

Now I can use Streams again, and also reactivemongo seems to be working fine.

Is there a specific reason why the dependency was bumped to 2.6.1 in a minor release of reactivemongo?

**Comment by cchantep** [comment]
Hi,

As indicated in the [compatibility nodes](http://reactivemongo.org/releases/0.12/documentation/release-details.html#compatibility), ReactiveMongo is compatible with required Play libraries from "2.3.13 to 2.5.9" (now up to 2.6.1).

If you want to use the latest ReactiveMongo but not the latest Play libraries, you can use standard SBT eviction (what's done by default with the [Play module](http://reactivemongo.org/releases/0.12/documentation/tutorial/play.html)).

    ("org.reactivemongo" %% "reactivemongo" % buildVersion).exclude("com.typesafe.play", "*")

> As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) is the "place to ask questions or get help" (not this issue tracker).

Best regards
