### ISSUE TITLE
gridfs.enumerate(file) hang since 0.12.1

### ISSUE THREAD

**Issue by nitrotm** [ReactiveMongo/ReactiveMongo#624]
### ReactiveMongo Version

0.12.1

### MongoDB version

3.4.1

### Operating System

`Linux 296314324e76 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux`

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

### Library Dependencies

akka-streams 2.4.14
reactivemongo-akkastream 0.12.1
play-framework 2.5.12
play2-reactivemongo 0.12.1

### Expected Behavior

Assuming I have a GridFS file and I call enumerate(file), I should be able to stream the resulting Enumerator using akka-stream through play http response:

```
val fs: GridFS[BSONSerializationPack.type] = ...
val gridFile: ReadFile[BSONSerializationPack.type, BSONValue] = ...

Result(
  ResponseHeader(OK),
  HttpEntity.Streamed(
    Source.fromPublisher(
      Streams.enumeratorToPublisher(
        fs.enumerate(gridFile).map( ByteString(_) )
      )
    ),
    Option(gridFile.length),
    gridFile.contentType
  )
)
```

### Actual Behavior

This works well using reactive-mongo 0.12.0, but when upgrading to 0.12.1, the http transfer never begins and so it seems the akka source is hang somewhere.

Looking at the commit between 0.12.0 and 0.12.1:

- Update to Scala 2.12.1 (#601)
- SSL/TLS Client Authentication (#606)
- Use requestId instead of channelId as awaiting response key
- Support MongoDB 3.4

So I assume it must be a bug introduced by one of the commit above, but as I am not a reactivemongo expert, I can't exclude that my use-case is flawed and was working before by chance.

Note: it could also be related to reactivemongo-akkastream project.

### Reproducible Test Case

A simple play controller will do:

```
package controllers

import javax.inject._

import akka.stream._
import akka.stream.scaladsl.Source
import akka.util.ByteString

import play.api._
import play.api.http.HttpEntity
import play.api.libs.concurrent.Execution.Implicits.defaultContext
import play.api.libs.streams._
import play.api.mvc._

import play.modules.reactivemongo._

import reactivemongo.api.{ BSONSerializationPack, Cursor }
import reactivemongo.api.gridfs.{ DefaultFileToSave, GridFS }
import reactivemongo.api.gridfs.Implicits._
import reactivemongo.bson._


@Singleton
class TestController @Inject() (implicit reactiveMongoApi: ReactiveMongoApi) extends Controller {
  def read = Action.async { request =>
    for {
      fs <- reactiveMongoApi.database.map( db => GridFS[BSONSerializationPack.type](db) )
      gridFile <- fs.find(BSONDocument("_id" -> BSONObjectID("58873a356400007f015b9c93"))).head
    } yield Result(
      ResponseHeader(OK),
      HttpEntity.Streamed(
        Source.fromPublisher(
          Streams.enumeratorToPublisher(
            fs.enumerate(gridFile).map( ByteString(_) )
          )
        ),
        Option(gridFile.length),
        gridFile.contentType
      )
    )
  }
}
```

**Comment by cchantep** [comment]
Hi,

As indicated in the guidelines, please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question/for help.

Best regards
