### ISSUE TITLE
Connection hangs when the primary "disappears" behind a VPN/virtualization platform

### ISSUE THREAD

**Issue by kastoestoramadus** [ReactiveMongo/ReactiveMongo#626]
### Are you looking for help?

We got bugfix but without CI tests. On test enviroment the bugfix fixes the bug. Writting CI test would complete the process. 

### ReactiveMongo Version
Latest

### MongoDB version
Latest

### Problem description

Connection hangs when the primary "disapears".

Protected Mongo database nodes are hosted on two datacentres A, B and C. A primary node and its secondaries are in DC A and B, an election arbiter is in DC C, and a StrongSwan VPN connection securely replicates data between DC A and B.

Consider a digital service with a frontend in the public zone, a microservice in the protected zone with 2 instances in each data centre, and a Mongo primary in DC A. Traffic is currently set as 50/50 between DC A and B.

![d1](https://cloud.githubusercontent.com/assets/6271645/22422265/68546d50-e6e3-11e6-83f4-e79980b0c5db.png)

Figure 1: 50/50 traffic, VPN OK, microservices OK

When the VPN fails in DC A, customers of your digital service will start to experience an outage. Mongo would detect a replication failure within 10-60 seconds, and elect a new primary in DC B within a further 10-60 seconds.

![d2](https://cloud.githubusercontent.com/assets/6271645/22422273/6cacc9ba-e6e3-11e6-9c78-b94743e45bc1.png)

Figure 2 - 50/50 traffic, VPN failure, microservices failing

At this point WebOps would move 100% traffic to DC B, and your digital service should recover. However, customers of your digital service will experience timeout errors for hours or even days afterwards, and your logs will show plenty of MongoError[‘socket disconnected’] error messages - even though the StrongSwan VPN connection was likely restored within a minute or two! What’s going on?

![d3](https://cloud.githubusercontent.com/assets/6271645/22422276/704cf8ba-e6e3-11e6-9eb3-6b86a994078a.png)

Figure 3 - 0/100 traffic, VPN OK, microservices still failing!

When the Mongo primary in DC A is lost ReactiveMongo expects a TCP reset packet, but it is not sent on VPN failure. This leaves the ReactiveMongo connections within the DC B microservice instances in a zombie-like state.

Connection hangs for 15 minutes. No configuration changes helped.

### Reproducible Test Case

It is reproducible with this repository with simplified enviroment: https://github.com/hmrc/mongo-driver-vpn

It was written specially for this bug.

### BugFix

https://github.com/opetch/ReactiveMongo/tree/zombies

**Comment by cchantep** [comment]
You can check 0.12.2-SNAPSHOT

**Comment by kastoestoramadus** [comment]
Seems to work.

**Comment by cchantep** [comment]
Thanks for the feedback
