### ISSUE TITLE
ReactiveMongo 0.12.1 not compiling on Windows: shaded not found

### ISSUE THREAD

**Issue by ProgramFOX** [ReactiveMongo/ReactiveMongo#636]
ReactiveMongo 0.12.1
Operating System: Windows 10
Java:
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
ITERATEES_VERSION: 2.4.6 (_edit_: it also errors when not specifying this)

I'm trying to compile ReactiveMongo for Lichess on my Windows machine using these steps:
```
git clone --depth 1 https://github.com/ReactiveMongo/ReactiveMongo --branch 0.12.1
cd ReactiveMongo
set ITERATEES_VERSION=2.4.6
sbt publish-local
```
(set ITERATEES_VERSION isn't necessary apparently, compilations also fails without)

publish-local errors on compilation:
```
[error] E:\Data\programming\lila\ReactiveMongo\driver\src\main\scala\core\actors.scala:26: not found: object shaded
[error] import shaded.netty.channel.group.{
```
Here's the full log: https://gist.github.com/ProgramFOX/874855d9e4299ab064921e4cb9916dc9

Thanks for taking a look into this!

**Comment by cchantep** [comment]
Hi,

This tracker is not the place for support or for ask question (see [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo)), but for confirmed issue.
