### ISSUE TITLE
macros-generated private field `forwardReader` never has usages

### ISSUE THREAD

**Issue by vn971** [ReactiveMongo/ReactiveMongo#641]
Hi. The current implementation of `Macros.handler`, `Macros.reader`, `Macros.writer` define unused fields `forwardReader` and `forwardWriter`. They should be deleted (to reduce jar sizes, to make scalac warnings go away and to remove dead code from the code base).

### ReactiveMongo Version 0.12.1
Also, same code in the master branch here: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/macros/src/main/scala-2.12/MacroImpl.scala#L11

### OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

### Expected Behavior
No dead code in macro-generated code. No scalac warnings on unused private variables

1. define `case class C(i: Int)`
2. enable `scalac` flag `"-Ywarn-unused"`
3. compile

### Actual Behavior
scalac shows warnings on unused private variable. The variable really has no usages in any imaginable scenario. There's just a private val defined without usages.

1. scalac shows warnings, variable really has no usages and is unnecessary

### Reproducible Test Case

see above

**Comment by cchantep** [comment]
Hi,

This lazy variable is indeed use in some case of recursive types, so it cannot be "just" removed.

**Comment by vn971** [comment]
@cchantep thanks for the response! Where is it used? I only see definitions: https://github.com/ReactiveMongo/ReactiveMongo/search?utf8=%E2%9C%93&q=forwardWriter&type=

**Comment by cchantep** [comment]
https://github.com/ReactiveMongo/ReactiveMongo/blob/master/macros/src/main/scala-2.12/MacroImpl.scala#L603

> Please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) (to keep this tracker clean for actionable ticket).

**Comment by vn971** [comment]
Thanks, now I see it (deeply hidden). Sorry for that. Will use the ML.
