### ISSUE TITLE
Overloaded apply() with no parameters break macros completely

### ISSUE THREAD

**Issue by MrBagheera** [ReactiveMongo/ReactiveMongo#645]
### ReactiveMongo Version

0.12.1 (Used to work at least in 0.10.5)

### Expected Behavior

BSON macros should ignore overloaded `apply` method with arguments different from `unapply` return type, including empty `apply()` overload.

### Actual Behavior

Having case class with overloaded `apply()` method (with 0 arguments) causes macros to produce methods that write and read empty `BSONDocument`.

PR with failing test will be submitted shortly.

**Comment by MrBagheera** [comment]
PR with failing unit test - https://github.com/ReactiveMongo/ReactiveMongo/pull/646

**Comment by cchantep** [comment]
Hi, as indicated in the project guidelines, please first use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo). Best regards

**Comment by MrBagheera** [comment]
Sorry. I read project guidelines, but I was so "100% sure that it is a bug" so I went straight to creating issue. Nevertheless, here is related [mailing list topic](https://groups.google.com/forum/?fromgroups&nomobile=true#!topic/reactivemongo/r7ZJxYZrmj0).
