### ISSUE TITLE
Automatic GridFS Index Creation

### ISSUE THREAD

**Issue by matteobovetti** [ReactiveMongo/ReactiveMongo#666]
Is it possible to add automatic GridFS indices creation?

https://docs.mongodb.com/v3.2/core/gridfs/#gridfs-indexes

**Comment by cchantep** [comment]
Hi, as indicated in the [guidelines](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question/discuss of possible feature request. Best regards.
