### ISSUE TITLE
Akka 2.5

### ISSUE THREAD

**Issue by thjaeckle** [ReactiveMongo/ReactiveMongo#667]
Akka 2.5 brings improvements in stream materialization performance so I guess Reactivemongo could also benefit from that. 
Are there plans to support akka 2.5?

**Comment by cchantep** [comment]
Hi, as [indicated](http://reactivemongo.org/releases/0.12/documentation/release-details.html#compatibility), compatibility of 0.12.3 is up to Akka 2.5.1.

> Please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question (not this issue tracker).

Best regards.
