### ISSUE TITLE
Joda DateTime Json Conversion not $date object, but long

### ISSUE THREAD

**Issue by DieterLi** [ReactiveMongo/ReactiveMongo#669]
I import reactivemongo.play.json._ in order to implicitly convert Joda DateTime to Json value. The expected reault would follow the principle of JsObject with "$date" property. But the reality is that being converted to long milliseconds, so does to the field in MongoDB database.

I want to know whether it will be changed to following the JSON conversion rules, or we have to provide the conversion by ourselves.

**Comment by cchantep** [comment]
Hi,

Thanks for your feedback.
As indicated in the [guide](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md), please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).

Best regards
