### ISSUE TITLE
Aggregate queries not passing cursor and fail

### ISSUE THREAD

**Issue by tomerf** [ReactiveMongo/ReactiveMongo#670]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
0.12.2

### MongoDB version (2.6, 3.0 / etc)
3.4

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
macOS 10.12.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
jdk1.8.0_121

When I call aggregate query the cursor isn't sent, causing mongo to fail because it exceeds the maxumum document size:

> MongoDB exception: CommandError[code=16389, errmsg=aggregation result exceeds maximum document size (16MB)

However, when I used the same call with the batchSize parameter it succeeded (no matter what value I passed).
In the mongod log I see the cursor parameter isn't passed when this is not specified.

### Reproducible Test Case

Example code not working:
```
somedb.aggregate1[MyObject](Match(selector),
      Lookup("otherdb", "somelist", "_id", "other_doc") ::
        Project(BSONDocument("_id" -> "$_id",
          "somefield" -> "$somefield",
          "somefield2" -> "$somefield2",
          "somelist" -> "$other_doc"
        ))).collect[List]()
```
Example code working:
```
somedb.aggregate1[MyObject](Match(selector),
      Lookup("otherdb", "somelist", "_id", "other_doc") ::
        Project(BSONDocument("_id" -> "$_id",
          "somefield" -> "$somefield",
          "somefield2" -> "$somefield2",
          "somelist" -> "$other_doc"
        )), batchSize = Some(50)).collect[List]()
```

P.S. This also happens with somedb.aggregate(...), the call above is how I "solved" it.

**Comment by cchantep** [comment]
This depends on the data aggregated, so I cannot see it as a driver bug and it seems normal to pass appropriate parameters.

**Comment by tomerf** [comment]
Actually, according to MongoDB it is a bug:

> Use of the aggregate command without the 'cursor' option is deprecated. See http://dochub.mongodb.org/core/aggregate-without-cursor-deprecation.

**Comment by cchantep** [comment]
"MongoDB 3.4 deprecates the use of aggregate command without the cursor option, unless the pipeline includes the explain option. When returning aggregation results inline using the aggregate command, specify the cursor option using the default batch size cursor: {} or specify the batch size in the cursor option cursor: { batchSize: <num> }."

- The driver is compatible from MongoDB 2.6, not only MongoDB 3.4.
- Even considering MongoDB 3.4, supported a deprecated option, which is still supported by MongoDB itself, can hardly be configured as a bug.

> As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md), please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).
