### ISSUE TITLE
mongodb 3.4 deprecation warning

### ISSUE THREAD

**Issue by ornicar** [ReactiveMongo/ReactiveMongo#677]
on 0.12.2, seeing this in the server logs:

```
2017-06-27T10:41:06.814+0200 W COMMAND  [conn399012] Use of the aggregate command without the 'cursor' option is deprecated. See http://dochub.mongodb.org/core/aggregate-without-cursor-deprecation.
```

**Comment by cchantep** [comment]
Right, this happens w/ such MongoDB version when using `.aggregate` which send an [`Aggregate`](http://reactivemongo.org/releases/0.12/api/index.html#reactivemongo.api.commands.AggregationFramework@AggregateextendsCollectionCommandwithCommandWithPack[AggregationFramework.this.pack.type]withCommandWithResult[AggregationFramework.this.AggregationResult]withProductwithSerializable) w/ an empty `Cursor` option.

There are other aggregation operators which use cursor, such as `.aggregateWith` or the most recent `.aggregatorContext` (all are test covered if looking for more examples).

Doc PR welcome ;-)
