### ISSUE TITLE
IndexManager.ensure doesn't throw and returns true even if index creation failed

### ISSUE THREAD

**Issue by jeep87c** [ReactiveMongo/ReactiveMongo#699]
#### Collection has records with duplicate value of field Bar, preventing the user of creating an unique index of field Bar

1. Add records for collection Foo with field Bar set to same value for some records (ensuring field Bar can't be unique)
2. Use IndexManager.ensure method adding a new unique Ascending index on field Bar
3. IndexManager.ensure method doesn't return true/false but throws the appropriate exception. Or at least returns false but it would break the contract, since true means it was successfully created and false means it was already created.

#### Collection has already one text index on one of its field preventing the user to create another index of type text.

1. Use IndexManager.ensure to create a text index on field Bar
2. Use IndexManager.ensure method again adding another text index on another field than Bar
3. IndexManager.ensure method doesn't return true/false but throws the appropriate exception. Or at least returns false but it would break the contract, since true means it was successfully created and false means it was already created.

#### Collection has records with duplicate value of field Bar, preventing the user of creating an unique index of field Bar

1. Add records for collection Foo with field Bar set to same value for some records (ensuring field Bar can't be unique)
2. Use IndexManager.ensure method adding a new unique Ascending index on field Bar
3. Method IndexManager.ensure returns true

#### Collection has already one text index on one of its field preventing the user to create another index of type text.

1. Use IndexManager.ensure to create a text index on field Bar
2. Use IndexManager.ensure method again adding another text index on another field than Bar
3. Method IndexManager.ensure returns true

### More info
So it feels like IndexManager ensure method is swallowing every MongoDB exception while trying to create a new index. It should probably return a more complex object than a Future[Boolean]. Something similar to GenericCollection.update method which is returning a Future[UpdateWriteResult].

**Comment by cchantep** [comment]
Hi, as indicated in the guidelines, first use the MailingList. Best regards.
