### ISSUE TITLE
Inserting lots of documents exceeds 16MB size limit

### ISSUE THREAD

**Issue by tomerf** [ReactiveMongo/ReactiveMongo#712]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
0.12.2, 0.12.7

### MongoDB version (2.6, 3.0 / etc)
3.4

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
macOS 10.12.6

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
jdk1.8.0_121

### Expected Behavior
All documents are written in the MongoDB collection.

### Actual Behavior
The documents are not written and MongoDB produces a backtrace in the logs, stating it received a request that exceeds the maximum BSON size.

### Reproducible Test Case
Both calls to bulkInsert on 0.12.2 and insert().many() on 0.12.7 fails:
```
val coll: BSONCollection = db.collection("mycoll")
val bsonList = List(BSONDocument(...), BSONDocument(...), ...)
// 0.12.2
coll.bulkInsert(bsonList.toStream, true)
// 0.12.7
coll.insert(ordered = true).many(bsonList)
```

**Comment by cchantep** [comment]
Hi,

As indicating in the [guide](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/CONTRIBUTING.md#reporting-issues), please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question/for help.

> Note that as the bulk insert/update are coverted by the current tests, without a reproducer nothing will be actionable.

Best regards.
