### ISSUE TITLE
Some tests are failing (0.12.7)

### ISSUE THREAD

**Issue by arminio** [ReactiveMongo/ReactiveMongo#714]
I have checked out the latest but I am getting a few of the tests failing when I run the following coomand:
sbt "test-only -- exclude mongo2"

(my mongo db version = v3.2.9 / Release 0.12.7 (#710) - SHA: 9534d24709ab284d280f1128ea2de73687f9df9e)

sbt output:
>16:48:32.414 ReactiveMongo WARN  [tests] :: Fails to stop the default driver: java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]
>[error] Error: Total 392, Failed 8, Errors 5, Passed 379
>[error] Failed tests:
>[error] 	UpdateSpec
>[error] 	CursorSpec
>[error] 	QueryAndWriteCommandSpec
>[error] Error during tests:
>[error] 	CommonUseCases
>[error] 	IndexesSpec
>[error] 	CollectionSpec
>[error] 	AggregationSpec
>16:48:32.421 ReactiveMongo WARN  [r.a.Driver] :: [Supervisor-2] Failed to close connections within timeout. Continuing closing of ReactiveMongo driver anyway.
>akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://reactivemongo/user/Supervisor-2#338642013]] after [2000 ms]
>	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334) ~[akka-actor_2.11-2.3.13.jar:?]
>	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[akka-actor_2.11-2.3.13.jar:?]
>	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) ~[scala-library-2.11.11.jar:?]
>	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[scala-library-2.11.11.jar:?]
>	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) ~[scala-library-2.11.11.jar:?]
>	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467) ~[akka-actor_2.11-2.3.13.jar:?]
>	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419) ~[akka-actor_2.11-2.3.13.jar:?]
>	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423) ~[akka-actor_2.11-2.3.13.jar:?]
>	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375) ~[akka-actor_2.11-2.3.13.jar:?]
>	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]
>[error] (ReactiveMongo/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
>[error] Total time: 311 s, completed 19-Oct-2017 16:48:33
>16:48:33.692 ReactiveMongo WARN  [r.a.Driver] :: [Supervisor-1] Failed to close connections within timeout. Continuing closing of ReactiveMongo driver anyway.
>akka.pattern.AskTimeoutException: Recipient[Actor[akka://reactivemongo/user/Supervisor-1#335818270]] had already been terminated.
>	at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132) ~[akka-actor_2.11-2.3.13.jar:?]
>	at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144) ~[akka-actor_2.11-2.3.13.jar:?]
>	at reactivemongo.api.Driver$class.askClose(Driver.scala:100) ~[classes/:?]
>	at reactivemongo.api.MongoDriver.askClose(MongoDriver.scala:29) ~[classes/:?]
>	at reactivemongo.api.MongoDriver.close(MongoDriver.scala:67) ~[classes/:?]
>	at UnresponsiveSecondarySpec$$anon$1.run(UnresponsiveSecondarySpec.scala:34) ~[test-classes/:?]

**Comment by cchantep** [comment]
Hi,

The traces pasted are warning not details about the failed.

Also as indicated, and considering that tests are running fine one the CI envs, please first use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to discuss/ask question.

Best regards
