### ISSUE TITLE
The latest version (0.12.7) doesn't work well with high concurrency scenes.

### ISSUE THREAD

**Issue by joymufeng** [ReactiveMongo/ReactiveMongo#721]
### JDK (Oracle 1.8.0_72)
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
### Library Dependencies
None.

### Expected Behavior
ReactiveMongo should work normally under the condition of 100 upserts/sec.

### Actual Behavior
Errors occur after several minutes: [error log](https://raw.githubusercontent.com/joymufeng/test-reactivemongo/master/src/main/scala/error.log).

#### MongoDB server
mongodb://test:test@106.14.154.101:27117/test?authMode=scram-sha1
MongoDB 3.4.6, 1G RAM, 1CPU, Ubuntu 14.04.5 LTS

#### Test client
Java 1.8.0_111, 16G RAM, Intel(R) Core(TM) i5-6400 CPU @ 2.7GHz, Windows 10

#### Test codes
In order to reproduce this issue as soon as possible, there are no extra indexes on the tested collection `stat-session`.  The same codes works well with ReactiveMongo 0.11.14.
https://github.com/joymufeng/test-reactivemongo

**Comment by a935855375** [comment]
I also meet this issue..

**Comment by cchantep** [comment]
Even after several minutes I don't reproduce the issue.

You can try 0.12.8-SNAPSHOT.

Also as [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md), please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) for discussion.

Best regards.

**Comment by joymufeng** [comment]
@cchantep This issue also exists in 0.12.8-SNAPSHOT:
```
[main] INFO reactivemongo.api.Driver - No mongo-async-driver configuration found
[main] INFO reactivemongo.api.Driver - [Supervisor-1] Creating connection: Connection-2
start ...
2017-11-16T12:03:04.619
[reactivemongo-akka.actor.default-dispatcher-6] INFO reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Starting the MongoDBSystem akka://reactivemongo/user/Connection-2
2017-11-16T12:03:34.691
2017-11-16T12:05:04.682
[reactivemongo-akka.actor.default-dispatcher-7] WARN reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Node[106.14.154.101:27117: Primary (10/10 available connections), latency=40495, authenticated=Set(Authenticated(test,test))] hasn't answered in time to last ping! Please check its connectivity
[reactivemongo-akka.actor.default-dispatcher-7] ERROR reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Oups. 5875 not found! complete message is Response(MessageHeader(126,1217839,5875,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=126, cap=126),ResponseInfo(-1756851257))
[reactivemongo-akka.actor.default-dispatcher-7] ERROR reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Oups. 5913 not found! complete message is Response(MessageHeader(126,1217840,5913,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=126, cap=126),ResponseInfo(-1950997288))
[reactivemongo-akka.actor.default-dispatcher-7] ERROR reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Oups. 5910 not found! complete message is Response(MessageHeader(126,1217841,5910,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=126, cap=126),ResponseInfo(-1554144800))
[reactivemongo-akka.actor.default-dispatcher-7] ERROR reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Oups. 5897 not found! complete message is Response(MessageHeader(126,1217842,5897,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=126, cap=126),ResponseInfo(2000543381))
[reactivemongo-akka.actor.default-dispatcher-7] ERROR reactivemongo.core.actors.MongoDBSystem - [Supervisor-1/Connection-2] Oups. 5353 not found! complete message is Response(MessageHeader(126,1217843,5353,1),Reply(8,0,0,1),LittleEndianHeapChannelBuffer(ridx=36, widx=126, cap=126),ResponseInfo(-1329029930))
...
```

**Comment by joymufeng** [comment]
@sgodbillon Hi sgodbillon, what do you think about this issue ?  It could be stably reproduced on our production servers (Ubuntu 14.04) and my development computer(windows 10) with MongoDB 3.2.9 and 3.4.6. After these errors occur, the application will be out of service immediately and couldn't recover from these errors.  We currently forced to downgrade to 0.11.14, because this issue doesn't exist in 0.11.14. It's really a serious issue and should seriously treated.

**Comment by cchantep** [comment]
@joymufeng As previously said, using the reproducer we cannot see the issue.

The [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) can be used to discussed, so that it can be actionable.
