### ISSUE TITLE
Cannot set batchSize for aggregation cursor

### ISSUE THREAD

**Issue by nebehr** [ReactiveMongo/ReactiveMongo#727]
**ReactiveMongo Version (0.12.7)
MongoDB version (3.6.0)
Operating System (Windows 10)
JDK (Oracle 1.8.0_152)**

**Expected Behavior**
It should be possible to configure batch size for getMore commands of an aggregation.

**Actual Behavior**
None of the existing `GenericCollection` methods (`aggregate`, `aggregateWith1`, `aggregatorContext`) allows to specify the size of getMore batches, only the initial batch size. It results in performance degradation when all aggregation results do not fit in the first batch. So, if an aggregation query produces, say, 110 documents and the initial batch size is 100, collecting it into a `List` will generate 11 commands to Mongo: one first batch of 100 and 10 batches of 1 each.

There is a discussion about this at https://groups.google.com/forum/?fromgroups#!searchin/reactivemongo/getmore|sort:date/reactivemongo/hXJgJld71nU/1hp4GkXiDgAJ but the responses seem to suggest there is no way currently to pass desired `QueryOpts.batchSize` for the getMore batches.

**Comment by cchantep** [comment]
See #733
