### ISSUE TITLE
Why is _tags mutable?

### ISSUE THREAD

**Issue by gabrieljones** [ReactiveMongo/ReactiveMongo#738]
https://github.com/ReactiveMongo/ReactiveMongo/blob/26c322f9a0aec66725933052758ca712ed0f1cea/driver/src/main/scala/api/ReadPreference.scala#L77

**Comment by gabrieljones** [comment]
If it has to be mutable then why is toString immutable?

**Comment by cchantep** [comment]
Due to deprecated constrictor/factory

**Comment by gabrieljones** [comment]
https://github.com/ReactiveMongo/ReactiveMongo/blob/26c322f9a0aec66725933052758ca712ed0f1cea/driver/src/main/scala/api/ReadPreference.scala#L91

Then toString should be `def` not `val`

**Comment by gabrieljones** [comment]
Same for 
https://github.com/ReactiveMongo/ReactiveMongo/blob/26c322f9a0aec66725933052758ca712ed0f1cea/driver/src/main/scala/api/ReadPreference.scala#L124
and
https://github.com/ReactiveMongo/ReactiveMongo/blob/26c322f9a0aec66725933052758ca712ed0f1cea/driver/src/main/scala/api/ReadPreference.scala#L157
and
https://github.com/ReactiveMongo/ReactiveMongo/blob/26c322f9a0aec66725933052758ca712ed0f1cea/driver/src/main/scala/api/ReadPreference.scala#L193

**Comment by AEtherSurfer** [comment]
Did this get fixed?
