### ISSUE TITLE
Deprecated find issues

### ISSUE THREAD

**Issue by borice** [ReactiveMongo/ReactiveMongo#775]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
play2-reactivemongo 0.16.0-play26
Play version 2.6.17

### MongoDB version (2.6, 3.0 / etc)
4.0.1

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Replaced deprecated "find()" usage to "find with optional projection"
2. Code compiles and works like before

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. Replaced deprecated "find()" usage to "find with optional projection"
2. Code does not compile (see below for details)

Details:
I replaced usages of the form `.find(Json.obj(...)).cursor[...]...` which were being flagged as deprecated [1], with `.find(Json.obj(...), None).cursor[...]...` but I am getting the following compilation errors [2]

[1]
```
Warning:(36, 18) method find in trait GenericCollection is deprecated (since 0.16.0): Use `find` with optional `projection`
      .flatMap(_.find(Json.obj("_id" -> bsonPhotoId)).one[PhotoEntity])
```

[2]
```
Error:(36, 22) ambiguous implicit values:
 both object BSONDocumentWrites in trait ImplicitBSONHandlers of type reactivemongo.play.json.package.BSONDocumentWrites.type
 and object JsObjectDocumentWriter in trait ImplicitBSONHandlers of type reactivemongo.play.json.package.JsObjectDocumentWriter.type
 match expected type play.api.libs.json.OWrites[J]
      .flatMap(_.find(Json.obj("_id" -> bsonPhotoId), None).one[PhotoEntity])
```

When I look at the ReactiveMongo code for the non-deprecated `find`, it looks like it supplies a default `Option.empty` value for the optional projection, if not specified at call time, however my code using `.find(Json.obj(...)).cursor...` seems to get the deprecated method, not the method with the default Option argument.

Any ideas?

**Comment by jbgi** [comment]
yes, see https://github.com/ReactiveMongo/ReactiveMongo/pull/770 and https://github.com/ReactiveMongo/ReactiveMongo/pull/765#discussion_r208033683 for more context.
