### ISSUE TITLE
Update reactivemongo.org

### ISSUE THREAD

**Issue by joe-mojo** [ReactiveMongo/ReactiveMongo#779]
A lots of links on http://reactivemongo.org are broken. 
It looks like the website is abandoned 😓

**Comment by cchantep** [comment]
The links are checked before publication, and is often checked.
Please be specific.

**Comment by joe-mojo** [comment]
- On page : http://reactivemongo.org/releases/0.1x/documentation/tutorial/play.html
  - link "API of this Play module" to https://oss.sonatype.org/service/local/repositories/releases/archive/org/reactivemongo/play2-reactivemongo_2.12/0.16.0/play2-reactivemongo_2.12-0.16.0-javadoc.jar/!/index.html
  - link "also available" to https://oss.sonatype.org/service/local/repositories/releases/archive/org/reactivemongo/reactivemongo-play-json_2.12/0.16.0/reactivemongo-play-json_2.12-0.16.0-javadoc.jar/!/index.html
  - etc. **All** links to oss.sonatype.org/* are broken

**Comment by masterclock** [comment]
the link maybe:
https://oss.sonatype.org/service/local/repositories/releases/archive/org/reactivemongo/play2-reactivemongo_2.12/0.16.0-play26/play2-reactivemongo_2.12-0.16.0-play26-javadoc.jar/!/index.html
note the `play26` after `0.16.0`, the version number has never be correct for years.
