### ISSUE TITLE
BSONDocumentFormat.reads from a file

### ISSUE THREAD

**Issue by kastoestoramadus** [ReactiveMongo/ReactiveMongo#786]
Hi,
I made a repo with a single failing test: https://github.com/kastoestoramadus/formatter-bug-test/blob/master/src/test/scala/TestRepositorySpec.scala

File to be read: https://github.com/kastoestoramadus/formatter-bug-test/blob/master/src/test/resources/feb2015NoPeriodOfAccounts.json

Made after trying to migrate to a newer version of your lib. Worked before. Only imports have changed.

If the usage is proper then this test proves a bug. If not, please help me understand what I do incorrectly.

**Comment by cchantep** [comment]
Doesn't reproduce. Please first use the [Mailinglist](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask for help/question (this tracker is for confirmed issued).

**Comment by kastoestoramadus** [comment]
My bad, sorry. Have a nice day.
