### ISSUE TITLE
Incorrect behavior when a heartbeat connection error occurs. (0.160, 0.16.1)

### ISSUE THREAD

**Issue by gatorcse** [ReactiveMongo/ReactiveMongo#794]
### ReactiveMongo Version
0.16.0, 0.16.1
### MongoDB version
3.4, but irrelevant to the issue
### Operating System
MacOS 10.14
### JDK
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Expected Behavior
1. Configure a seed list, with at least one of the seeds unreachable.
2. Initialize the driver.
3. Driver fails to connect to the bad seed.
4. Driver _*DOES NOT*_ immediately attempt to reconnect, rather it sets the server state to `UNKNOWN` and waits `heartbeatFrequencyMS` for the next regularly scheduled check.

### Actual Behavior

4. Driver immediately (0.16) or quickly (0.16.1) attempts to check again, fails again, checks again, etc. Continuously attempts to connect and fails, consuming a lot of CPU and spamming the logs.

[MongoDB Specifications](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#network-error-when-reading-or-writing) states:

> Clients MUST NOT request an immediate check of the server; since application sockets are used frequently, a network error likely means the server has just become unavailable, so an immediate refresh is likely to get a network error, too.
>
> The server will not remain Unknown forever. _**It will be refreshed by the next periodic check**_ or, if an application operation needs the server sooner than that, then a re-check will be triggered by the server selection algorithm.

This suggests that the driver should wait for the next heartbeat, rather than immediately reattempt. In this case, since there are other (valid) seeds in the initial seed list, server selection should not need to trigger a re-check.

This issue was addressed recently by adding the `rm.reconnectDelayMS` option to manually delay the reconnection attempt, but that shouldn't be needed as the specification says that they shouldn't be attempting to immediately reconnect anyway.

Related: #787: Manually specify reconnect delay.

### Reproducible Test Case

Simply attempt to use a driver created with multiple hosts in its seed list, one of which is unreachable. This probably also occurs if a previously known host becomes unreachable.

**Comment by xdev-developer** [comment]
>1. Driver immediately (0.16) or quickly (0.16.1) attempts to check again, fails again, checks again, etc. Continuously attempts to connect and fails, consuming a lot of CPU and spamming the logs.

I've found that, when connection fails with `No primary node is available` application start producing tons of threads. 
I think this is related.

**Comment by cchantep** [comment]
- `hearbeatFrequencyMS` is not a term from the specification: https://github.com/mongodb/specifications/search?q=hearbeatFrequencyMS&unscoped_q=hearbeatFrequencyMS

> "Clients MUST NOT request an immediate check of the server; since application sockets are used frequently, a network error likely means the server has just become unavailable, so an immediate refresh is likely to get a network error, too."
>
> "The server will not remain Unknown forever. It will be refreshed by the next periodic check or, if an application operation needs the server sooner than that, then a re-check will be triggered by the server selection algorithm."
>
> This suggests that the driver should wait for the next heartbeat, rather than immediately reattempt. In this case, since there are other (valid) seeds in the initial seed list, server selection should not need to trigger a re-check.
>
> This issue was addressed recently by adding the rm.reconnectDelayMS option to manually delay the reconnection attempt, but that shouldn't be needed as the specification says that they shouldn't be attempting to immediately reconnect anyway.

That's already done, and there is already a default value of `1000` (1s) for the reconnection delay if not overriden in configuration.

**Comment by gatorcse** [comment]
@cchantep My apologies, I put a typo in my original comment (hear**~~t~~**beatFrequenceMS). The flag is documented in the specification [here](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#heartbeatfrequencyms).

While yes, there is a default of 1 second now for reconnect, the expectation is for the default to be 10 seconds. Also, the [expectation](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#heartbeatfrequencyms) is to configure it with `heartbeatFrequencyMS`. I know we have the `rm.reconnectDelayMS` flag now for throttling reconnection attempts, but this issue bit us because we were expecting to be able to configure the `heartbeatFrequencyMS` flag. Using the `heartbeatFrequencyMS` flag as expected would remove the need for a custom `rm.reconnectDelayMS` flag.

**Comment by csaltos** [comment]
Sadly this bug is appearing again at ReactiveMongo version 0.18.8, if that's OK with you guys, I'll open a new ticket to tackled this new incarnation of this sad error
