### ISSUE TITLE
Problems connecting to MongoDB Atlas using SRV seed list

### ISSUE THREAD

**Issue by borice** [ReactiveMongo/ReactiveMongo#797]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)

0.16.2

### MongoDB version (2.6, 3.0 / etc)

4.0.6 (Atlas)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.14.3

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

### Library Dependencies

Play 2.6.21

### Expected Behavior

1. [Create free deployment of MongoDB Atlas](https://www.mongodb.com/download-center/cloud) 
2. Attempts to connect to it via ReactiveMongo using the Atlas-recommended connection string: `mongodb+srv://<user>:<pass>@<host>/<db>?retryWrites=true` would work as expected with no warning or error messages produced.
3. A query can be successfully run (for example, to retrieve some data from a collection) 

### Actual Behavior

1. No issues here
2. The connection attempt using the connection string format from above produces the following messages in the application console  (might be related to #791):
```
rec = db-cluster-test-qfedj.mongodb.net.	60	IN	TXT	"authSource=admin&replicaSet=db-cluster-test-shard-0"
[warn] r.a.MongoConnection - Connection option 'authSource' deprecated: use option 'authenticationDatabase'
```
3. An error is generated when the query is attempted:
```
 java.lang.IllegalArgumentException: The connection URI contains unsupported options: retryWrites, replicaSet
	at reactivemongo.api.MongoDriver.connection(MongoDriver.scala:157)
	at reactivemongo.api.MongoDriver.connection(MongoDriver.scala:173)
	at play.modules.reactivemongo.DefaultReactiveMongoApi.connection$lzycompute(DefaultReactiveMongoApi.scala:45)
	at play.modules.reactivemongo.DefaultReactiveMongoApi.connection(DefaultReactiveMongoApi.scala:44)
	at play.modules.reactivemongo.DefaultReactiveMongoApi.database(DefaultReactiveMongoApi.scala:53)
	at controllers.HomeController.db(HomeController.scala:22)
```

### Reproducible Test Case

Here's an [example project](https://github.com/borice/play-reactivemongo-atlas) that showcases the problem. Its configuration uses a real MongoDB Atlas endpoint which I provide only for quick verification of the problem. Access to it will be removed in the near future. 

The `conf/application.conf` contains some example configuration that produces the error, and another that works.

This sample app was based on `sbt new playframework/play-scala-seed.g8`.  Changes to this sample app are captured in commit https://github.com/borice/play-reactivemongo-atlas/commit/67e6fda71c53b5294e8b2db902500201408d401d

**Comment by avdv** [comment]
You're using Play 2.7 but the play26 dependency of reactivemongo. That is not supposed to work.

**Comment by borice** [comment]
@avdv Thanks. My mistake.  I copied the dependency from my "real" project which uses 2.6.21, but the `sbt new playframework/play-scala-seed.g8` generated a Play 2.7 project.  I just updated my example project to use the correct dependency for Play 2.7.

However, this doesn't change anything with respect to the error I reported.  The same errors happen with the correct dependency also.

**Comment by avdv** [comment]
We are also using MongoDB Atlas, and we have no problem connecting to the nodes...

**Comment by borice** [comment]
Are you using the `mongodb+srv://...` connection method?
I know it will work if you manually specify all the replica sets... but this bug report is for whenever you use SRV discovery.
If you have it working with SRV...can you tell me what I did wrong in my example project?
Thank you.

**Comment by avdv** [comment]
Oh, you have enabled `mongodb.connection.strictUri ` mode, which causes the exception.

**Comment by borice** [comment]
@avdv Thank you! Wow... can't believe I missed that.  That setting was also from the original project before I decided to try out Atlas.  I feel dumb.  Thanks for showing the light.  I'll close this issue.

However, before I close this, from [Atlas FAQ](https://docs.atlas.mongodb.com/faq/#how-does-service-fullname-deliver-high-availability) I see:

> MongoDB 3.6+ drivers can automatically retry certain write operations a single time. Retryable writes provide built-in handling of automatic failovers and elections. The cluster must run MongoDB 3.6 or greater to support retryable writes. See retryable writes for complete documentation and requirements.

>To enable this feature, add retryWrites=true to your Atlas URI connection string. See Connect via Driver for details on connecting to a Atlas cluster using a URI connection string.

It seems to me that the `retryWrites=true` is a driver responsibility.  Even though removing the `mongodb.connection.strictUri` made things work, the ReactiveMongo driver still outputs a warning:

>[warn] r.a.MongoDriver - Some options were ignored because they are not supported (yet): retryWrites, replicaSet

which indicates that `retryWrites` is not currently a supported feature.  This can present problems if ReactiveMongo is used with Atlas during failover events.

>  Retryable writes provide built-in handling of automatic failovers and elections. (from Atlas FAQ)

**Comment by cchantep** [comment]
> "**can** automatically retry certain write operations a single time

... Not must ...

... and ReactiveMongo provide a failover mechanism, mentioned in the documentation.

**Comment by borice** [comment]
Thank you @cchantep 

Here's the documentation that Cédric is referring to, for future reference:
http://reactivemongo.org/releases/0.1x/documentation/advanced-topics/failoverstrategy.html

I think the "can" in the fragment you quoted was not originally intended to mean an option, but more a statement of fact about what *their* officially-provided drivers support.   

Since ReactiveMongo by default retries all operations according to the default Failover Strategy, then I guess the `retryWrites` option is not necessary as it is the default behavior.

> The default FailoverStrategy retries 5 times, with 500 ms between each attempt.

Thank you both, again, for your help.
