### ISSUE TITLE
MongoDBSystem oom.

### ISSUE THREAD

**Issue by coding4m** [ReactiveMongo/ReactiveMongo#811]
ReactiveMongoVersion 0.16.3

on MongoDBSystem line 129-131:
`  private lazy val history =
    Queues.newConcurrentLinkedQueue(
      EvictingQueue.create[(Long, String)](historyMax))`

it will retain all nodeset event.

**Comment by cchantep** [comment]
`EvictingQueue.create[(Long, String)](historyMax)` <-- `historyMax`

**Comment by coding4m** [comment]
??? what's means ???
see MAT Leaks:
`One instance of "reactivemongo.core.actors.StandardDBSystem" loaded by "sun.misc.Launcher$AppClassLoader @ 0x646001748" occupies 6,232,092,960 (98.60%) bytes. 

Keywords
reactivemongo.core.actors.StandardDBSystem
sun.misc.Launcher$AppClassLoader @ 0x646001748`

`Label	Number of Objects	Used Heap Size	Retained Heap Size
java.util.concurrent.ConcurrentLinkedQueue
All 1 objects	1	24	6,232,092,040
reactivemongo.core.actors.RequestTracker
All 1 objects	1	24	336
reactivemongo.core.errors.GenericDriverException
All 1 objects	1	40	176
java.lang.String
All 1 objects	1	24	96
scala.collection.mutable.ListBuffer
All 1 objects	1	32	56
reactivemongo.util.LazyLogger$LazyLogger
All 1 objects	1	24	24
reactivemongo.com.google.common.collect.Synchronized$SynchronizedQueue
All 1 objects	1	24	24
reactivemongo.core.actors.MongoDBSystem$IsMasterRequest$
All 1 objects	1	16	16
reactivemongo.core.actors.MongoDBSystem$$Lambda$827
All 1 objects	1	16	16
reactivemongo.core.actors.MongoDBSystem$NoJob$
All 1 objects	1	16	16
reactivemongo.core.actors.MongoDBSystem$$anonfun$closing$1
All 1 objects	1	16	16

Total: 11 entries
11	256	6,232,092,816
`

**Comment by mzsnelling** [comment]
This issue is affecting me too. The problem is the lines that have been pointed out by @coding4m:

    private lazy val history =
      Queues.newConcurrentLinkedQueue(
        EvictingQueue.create[(Long, String)](historyMax))

`Queues.newConcurrentLinkedQueue` creates a new ConcurrentLinkedQueue from the elements of an existing queue (the empty EvictingQueue), rather than wrapping around an existing queue. Unlike the EvictingQueue, this ConcurrentLinkedQueue is unbounded in size, and will continue to grow until the JVM runs out of memory.
