### ISSUE TITLE
Feature: balancing channel handling

### ISSUE THREAD

**Issue by riomus** [ReactiveMongo/ReactiveMongo#827]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)

0.17.1

### MongoDB version (2.6, 3.0 / etc)

not important

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

not important

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

not important

### Library Dependencies

not important

### Expected Behavior

During channel selection, channels that do not have running queries should be selected with higher priority, than channels with running operations. Priority queue could be used for that.

### Actual Behavior

Channels are selected using round-robin only taking into account maxInFlightRequestsPerChannel.

Would you accept a pull request for that?

**Comment by cchantep** [comment]
Pull request welcome (BTW [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) is there to ask question/discuss feature request).
