### ISSUE TITLE
partialFilter doesn't work together with sparse = true

### ISSUE THREAD

**Issue by maxmiholap** [ReactiveMongo/ReactiveMongo#830]
### Are you looking for help?

This tracker is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, the best place to start is with either the [users mailing list](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo).

This tracker is for confirmed issue or actionable feature request, used to manage and track the development of ReactiveMongo.

### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
0.17.0

### MongoDB version (2.6, 3.0 / etc)
3.6.10

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS  10.14.5
> Use `uname -a` if on Linux.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

> Paste the output from `java -version` at the command line.

### Library Dependencies

If this is an issue that involves integration with other frameworks (e.g. Playframework), include the exact versions the other frameworks.

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. create Index with partialFilter = Some(...), sparse = true
2. run ensureIndex
3. get successfully created index on mongo collection with partialFilter and sparse option as true

### Actual Behavior
index was not created

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behaviour actually is -- instead, say "BSONCollection.drop() fails with 'command drop failed because the 'ok' field is missing or equals 0'"  Copy and paste logs, and include any URLs. Turn on internal SLF4J logging if there is no log output (e.g. with Play/logback logging `<logger name="reactivemongo" value="TRACE"/>`).

1.
2.
3.

### Reproducible Test Case

Please provide a PR with a failing test.  

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

**Comment by cchantep** [comment]
Hi,

Please first use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question/for help, this tracker is for confirmed issue/actionable feature request.

Also note that [index/partialFilter is convered with test](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/test/scala/IndexesSpec.scala#L230), with no error detected for now.

Unless a minimal reproducer is provided, this issue is closed for now.
