### ISSUE TITLE
MongoDB connection created without `name` and without client metadata

### ISSUE THREAD

**Issue by eshel** [ReactiveMongo/ReactiveMongo#845]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
0.16.0 and 0.18.2

### MongoDB version (2.6, 3.0 / etc)
3.4.18

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Any Linux and MacOS

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_144"

### Expected Behavior

When creating a mongo driver & connection pool pool like this:
```
  lazy val driver = new MongoDriver
  lazy val connection: MongoConnection = driver.connection(
    nodes = servers,
    options = connectionOptions,
    name = serviceName)
```

We expect the Mongo connection to be initialized with a connection name and client metadata.

This can be verified by running a mongo query listing conections: `db.currentOp(true).inprog`, and having the results array members contain field `appName` as well as `clientMetadata`. 

Example of such output (when using Robo3T tool as client):

```
  {
    "desc": "conn183",
    "threadId": "0x70000687d000",
    "connectionId": 183,
    "client": "127.0.0.1:54338",
    "appName": "robo3t",
    "clientMetadata": {
      "application": {
        "name": "robo3t"
      },
      "driver": {
        "name": "MongoDB Internal Client",
        "version": "3.4.3-10-g865d2fb"
      },
      "os": {
        "type": "Darwin",
        "name": "Mac OS X",
        "architecture": "x86_64",
        "version": "18.6.0"
      }
    },
    "active": false
  },
```

### Actual Behavior

Actual connections created by reactivemongo do not include above fields, and look like this:

```
    {
        "desc" : "conn31319",
        "threadId" : "140101014599424",
        "connectionId" : 31319,
        "client" : "10.244.17.1:46926",
        "active" : false
    },
```

This is despite having initialised the `name` parameter above (which should correlate to `appName` in the mongo server-side client connection list).

When having hundreds of concurrent connections to a mongo server, not having this parameter passed makes observability of mongodb connections difficult.

**Comment by cchantep** [comment]
`appName` is only working in MongoDB >4 (and undocumented).
