### ISSUE TITLE
 document delete

### ISSUE THREAD

**Issue by MdMahadiaHossain** [ReactiveMongo/ReactiveMongo#877]
### Expected Behavior 

Please describe the expected behavior of the issue, starting from the first action.

1.  document will be deleted if I call  collection.map(_.delete(true).one(Json.obj("_id" -> Some(_id))))

### Actual Behavior

case class Document( _id: Option[BSONObjectID], something:String)

If I call 
def delete( id:String) = collection.map(_.delete(true).one(Json.obj("_id" -> Some(id))))

ok returns true but document is not deleted.

**Comment by cchantep** [comment]
Hi,
As indicated, this tracker is for confirmed issue.
Please use the [mailing list](https://groups.google.com/forum/m/#!forum/reactivemongo) to ask for help.
Best regards
