### ISSUE TITLE
Incorrect behavior when a heartbeat connection error occurs. (0.18.8)

### ISSUE THREAD

**Issue by csaltos** [ReactiveMongo/ReactiveMongo#894]
**ReactiveMongo Version**

0.18.8

**MongoDB version**

3.4, but irrelevant to the issue

Operating System

**Linux Debian 9**

**JDK**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Scala version**

2.12.10

### Reproduction steps

* Configure a node list, with at least one of the node unreachable

* Initialize the driver.

* Set the unreachable node back again to reach

### Current Behavior

Driver reports tons of warnings with this messages:

reactivemongo.core.actors: [Supervisor-1/Connection-1] Invalid node status Primary for server1 (expected: Unknown); Fallback to Unknown status

reconnecting at every operation even when the all node are OK and reachable (by the way, the service continues but a lot slower and with tons of noise)

### Expected behavious

The drivers status of nodes is correct reflecting the servers up and running (or down and excluded) but not the false status and reconnecting all the time

**Comment by csaltos** [comment]
This is a reappearing bug from the 0.16.x versions -> https://github.com/ReactiveMongo/ReactiveMongo/issues/794 (fixed at a minor 0.16.x version, OK at 0.17.x but now broken again at 0.18.x)

**Comment by cchantep** [comment]
Hi, without a reproducer, this is not actionable and should be first discussed/qualified on the [mailing list](https://groups.google.com/forum/m/#!forum/reactivemongo).
