### ISSUE TITLE
Suggestion: rename "SumAll" to "CountAll" for clarity in GroupAggregation -nt-

### ISSUE THREAD

**Issue by borice** [ReactiveMongo/ReactiveMongo#943]

**Comment by cchantep** [comment]
As [indicated](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help), this tracker is not for question or suggestion/discussion. Please use the mailing list.

Anyway, `SumAll` being based on `$sum` this renaming would make sense to me.
