### ISSUE TITLE
Is not possible to create an Index with version 0.20.3

### ISSUE THREAD

**Issue by rodrigogdea** [ReactiveMongo/ReactiveMongo#950]
I have change to the latest version (0.20.3) and now I cant create a index due to compilation error. I didn't find documentation to check. Any suggestion?
![image](https://user-images.githubusercontent.com/8377513/76461827-62759d80-63bf-11ea-8d0b-76abb10289f6.png)
 
![image](https://user-images.githubusercontent.com/8377513/76461921-8a650100-63bf-11ea-8274-133ae0704726.png)

Thanks!!

**Comment by cchantep** [comment]
Hi,

These cases are covered in [tests](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/test/scala/IndexesSpec.scala).

Rather use the [MailingList](https://groups.google.com/forum/m/#!forum/reactivemongo) to ask questions/for help, rather than the issue tracker.

Best regards
