### ISSUE TITLE
Text Search In MongoDB 2.4 (New Feature)

### ISSUE THREAD

**Issue by reyjexter** [ReactiveMongo/ReactiveMongo#99]
I wonder if this is something reactivemongo will support:

http://docs.mongodb.org/manual/core/text-search/

Thanks

**Comment by zcsongor** [comment]
And what to do in version 3.0? I'm a bit lost (and a beginner as well :P) .
Thanks!

**Comment by cchantep** [comment]
Please use the [user MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask questions. Best regards.
